#!/usr/bin/env python

import logging
from pymongo import MongoClient
from credentials import DBNAME, DBUSER, DBPASS, DBAUTH

# Enable logging
logging.basicConfig(format='%(asctime)s - %(name)s:%(lineno)d - %(levelname)s - %(message)s',
                    level=logging.INFO)

logger = logging.getLogger(__name__)

# MongoDB connection
client = MongoClient()
db = client[DBNAME]
db.authenticate(DBUSER, DBPASS, source=DBAUTH)

CZONES_CONTENTS = [
{"_id": 512, "fnewid":  "ACBZPl5iVicBcwVkDTVTZQB0AzdSPQRvA2ECL1AzAD8GZFdsW2NTYVUyBzYBbwRr", "fstate":  "Aceh", "fdescr":  "Aceh Barat", "ftzone": 7, "flstfl": 0}, 
{"_id": 513, "fnewid":  "CytQN1tnVyZXJVMyWWECNVYiVGAGaQBrVTcGK1AzWmUAYgc8ATkENgdgUmMIZgBv", "fstate":  "Aceh", "fdescr":  "Aceh Barat Daya", "ftzone": 7, "flstfl": 0}, 
{"_id": 514, "fnewid":  "BycFYgA8BndaKAZnDTVWZgx4BzNQPwBrVzVWewBjCTZaOFFqWmIDMQBnBzZeMFU6", "fstate":  "Aceh", "fdescr":  "Aceh Besar", "ftzone": 7, "flstfl": 0}, 
{"_id": 515, "fnewid":  "AyNTNAk1USAFd1Y3CzMCMwZyVGAFagVuA2EHKlEyAT4FZwI5DzcAMgNkUmNdMwBv", "fstate":  "Aceh", "fdescr":  "Aceh Jaya", "ftzone": 7, "flstfl": 0}, 
{"_id": 516, "fnewid":  "V3dVMgwwUSBUJlc2XmYKOARwAjZSPVU%2BBmRVeFIxDzAGZAE6CDACMARjVWMOYFA1", "fstate":  "Aceh", "fdescr":  "Aceh Selatan", "ftzone": 7, "flstfl": 0}, 
{"_id": 517, "fnewid":  "UHADZAA8VSQCcFEwCjIGNQZyU2dRPlA7BGYNIAFiAD9SMAY9CjJWZAViAzVdM1Yz", "fstate":  "Aceh", "fdescr":  "Aceh Singkil", "ftzone": 7, "flstfl": 0}, 
{"_id": 518, "fnewid":  "UnIFYlxgBndQIgVkXGRTb1YiBzMEawVuDG4BLFEyCzQCYA02WmIDMQptVWMNY1I3", "fstate":  "Aceh", "fdescr":  "Aceh Tamiang", "ftzone": 7, "flstfl": 0}, 
{"_id": 519, "fnewid":  "BSVTNA4yVCVSIAtqDTUFOAF1BjIBbgdsVTcALQZlAD8HZQU%2BWmJVZ1UyWG5dM1A1", "fstate":  "Aceh", "fdescr":  "Aceh Tengah", "ftzone": 7, "flstfl": 0}, 
{"_id": 520, "fnewid":  "AyNTNF1hAXBaKANiWWIANAB0UWUEawVuBmQGKwNgDTIFZwE6ATkDMQRjUmRbNQdi", "fstate":  "Aceh", "fdescr":  "Aceh Tenggara", "ftzone": 7, "flstfl": 0}, 
{"_id": 521, "fnewid":  "ASEAZwk1XC1QIgVkCTJWYwN3BDBQPwNoAGJRfFs4AD8HZVJpATkOPAJlAzUPYVM2", "fstate":  "Aceh", "fdescr":  "Aceh Timur", "ftzone": 7, "flstfl": 0}, 
{"_id": 522, "fnewid":  "BiYHYAs3VicFdwRlDDcHMQRwBDADbAVuUDIHKlEyWmUAYg02WmJSYFUyVmBaNABl", "fstate":  "Aceh", "fdescr":  "Aceh Utara", "ftzone": 7, "flstfl": 0}, 
{"_id": 523, "fnewid":  "V3cFYg0xUyJaKAFgCjEDNFElBzNRPgdsUjANIAFiAT4AYgA7DjYCMAptU2VeMAFk", "fstate":  "Aceh", "fdescr":  "Bener Meriah", "ftzone": 7, "flstfl": 0}, 
{"_id": 524, "fnewid":  "UXFTNA4yUyJUJgprDTYLOw15V2MFagRvVzVRfFIxWWYBYwU%2BCjJVZwViBTMLZVw5", "fstate":  "Aceh", "fdescr":  "Bireuen", "ftzone": 7, "flstfl": 0}, 
{"_id": 525, "fnewid":  "ACBRNgA8USBRI1EwCzAENQN3ATUDbAZtAmANIAdkDzBQMgI5CTEGNFUyVmBaNAdi", "fstate":  "Aceh", "fdescr":  "Gayolues", "ftzone": 7, "flstfl": 0}, 
{"_id": 530, "fnewid":  "VXUAZw8zBHUGdFc2CjAKPlAkCj4HaAFqDG5WewFiXmEFZ1VuXGQFN1I1V2EIZgRh", "fstate":  "Aceh", "fdescr":  "Banda Aceh Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 532, "fnewid":  "UHAEYwg0VidSIAFgDTcDNVYiCj4BbgZtVTcFKFIxXGNTMVJpXGQHNVYxUGYNYwNm", "fstate":  "Aceh", "fdescr":  "Langsa Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 533, "fnewid":  "BCRQNws3VCVaKFQ1XWdXYARwU2cCbVc8AmADLgBjWWYAYgI5CjJWZFUyAjQPYVUw", "fstate":  "Aceh", "fdescr":  "Lhokseumawe Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 534, "fnewid":  "BydSNQE9AHECcAdmCTMHNwF1U2cNYgVuAWMGKwNgCDdXNVZtDjZWZAFmBDIAblw5", "fstate":  "Aceh", "fdescr":  "Sabang Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 531, "fnewid":  "ACBWMQg0AXBQIgFgCjAHMgx4UGQFagdsBWdRfFc0AD8BYww3CjIENgBnWG5cMlYz", "fstate":  "Aceh", "fdescr":  "Subulussalam Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 526, "fnewid":  "BCRUM1xgUCFaKFMyAToLOVcjBTFVOgRvUDIMIVEyCDcHZVVuW2MFNwZhAzVZN1E0", "fstate":  "Aceh", "fdescr":  "Naganraya", "ftzone": 7, "flstfl": 0}, 
{"_id": 527, "fnewid":  "AyNQN1tnVCVXJQJjXGcGNQB0BDBXOAVuDW8EKVs4CDdQMgQ%2FXWUHNQptVmBeMABl", "fstate":  "Aceh", "fdescr":  "Pidie", "ftzone": 7, "flstfl": 0}, 
{"_id": 528, "fnewid":  "BSUDZAo2XSwAcgFgWmEGOgx4BTEBblA7AGJWewZlCjVTMVZtXmZSYAtsVmAKZAdi", "fstate":  "Aceh", "fdescr":  "Pidie Jaya", "ftzone": 7, "flstfl": 0}, 
{"_id": 529, "fnewid":  "BiYCZQ0xB3ZbKQtqW2AHOgJ2BTFRPgdsUjAMIQNgDzAHZVdsDjZRYwZhADYJZwBl", "fstate":  "Aceh", "fdescr":  "Simeulue", "ftzone": 7, "flstfl": 0}, 
{"_id": 784, "fnewid":  "V3dQNwg0XSwCcAVmDD1QYAJ2Cj4MY1c8VjRXelY1DzBRM1JpATkGNARjWG5eMAdi", "fstate":  "Bali", "fdescr":  "Badung", "ftzone": 8, "flstfl": 0}, 
{"_id": 785, "fnewid":  "VXUFYgs3UiNWJAppDz5XZgF1V2MAb1U%2BVTcFKANgXGMHZQM4WmIHNQdgV2ENYwFk", "fstate":  "Bali", "fdescr":  "Banglio", "ftzone": 8, "flstfl": 0}, 
{"_id": 786, "fnewid":  "ACBSNQ0xXC0HdVQ3ATALOQx4BTEDbFU%2BDW8FKFo5AD9QMgY9W2NWZARjADYIZl04", "fstate":  "Bali", "fdescr":  "Buleleng", "ftzone": 8, "flstfl": 0}, 
{"_id": 787, "fnewid":  "BydYP1tnBHVVJ1EyWmsHNFQgBTFRPlM4DW9Sf1MwAT5VN1dsDDRRY1E2UGYJZ1I3", "fstate":  "Bali", "fdescr":  "Gianyar", "ftzone": 8, "flstfl": 0}, 
{"_id": 788, "fnewid":  "ASECZQk1UiMCcAZlATBQbFcjBDBXOFM4AGJWe1EyWmVWNAU%2BWmJVZwptVGJdM1w5", "fstate":  "Bali", "fdescr":  "Jembrana", "ftzone": 8, "flstfl": 0}, 
{"_id": 789, "fnewid":  "BSVUMwk1VyZWJAtoDj8BPFcjV2NSPVI5B2UDLlEyDTJTMVVuWmIENgZhUWcMYlYz", "fstate":  "Bali", "fdescr":  "Karangasem", "ftzone": 8, "flstfl": 0}, 
{"_id": 790, "fnewid":  "VnZZPgA8UyIFdwBjDT0KPlMnADQCbVM4VTcFKFc0DTJRM1BrXmYAMgdgAjQIZgdi", "fstate":  "Bali", "fdescr":  "Klungkung", "ftzone": 8, "flstfl": 0}, 
{"_id": 792, "fnewid":  "V3dSNVpmVCVWJAdkDz8CNAdzBDAHaFU%2BUDICL1o5CzQBYwA7CjIAMlUyUmQAbl04", "fstate":  "Bali", "fdescr":  "Denpasar Kota", "ftzone": 8, "flstfl": 0}, 
{"_id": 791, "fnewid":  "VnYAZwwwA3IAclQ3Xm5XYlMnCz8DbFc8UjBRfFQ3DTJTMQA7XGRVZwBnUmQLZQNm", "fstate":  "Bali", "fdescr":  "Tabanan", "ftzone": 8, "flstfl": 0}, 
{"_id": 651, "fnewid":  "AyNWMQE9USBbKQZkDTFTZgdzBTFQPw5lDG4FKFAzAD9TMQ02WWFUZgNkAjQLZVA1", "fstate":  "Bangka Belitung", "fdescr":  "Bangka", "ftzone": 7, "flstfl": 0}, 
{"_id": 652, "fnewid":  "BSUAZ1pmBndVJ1c1AT0EMgdzUGRXOFI5B2UFKFMwXGNSMFFqXWVWZFI1BzFaNANm", "fstate":  "Bangka Belitung", "fdescr":  "Bangka Barat", "ftzone": 7, "flstfl": 0}, 
{"_id": 653, "fnewid":  "AyMFYgo2BHVXJQtpAT0HMFMnVmINYlU%2BBmQNIFU2WWZUNgc8DzcHNVE2BTMLZVA1", "fstate":  "Bangka Belitung", "fdescr":  "Bangka Selatan", "ftzone": 7, "flstfl": 0}, 
{"_id": 654, "fnewid":  "AyMAZwE9UCFaKAtpCzdWZgVxBDAHaABrAWMHKlEyCDcFZ1BrW2MAMgBnUmQPYV04", "fstate":  "Bangka Belitung", "fdescr":  "Bangka Tengah", "ftzone": 7, "flstfl": 0}, 
{"_id": 655, "fnewid":  "BiZVMg0xUiNRI1Y0WWUBMAx4UGQAbwFqBmQDLlU2CzQFZwc8WWEOPFE2UWcKZAZj", "fstate":  "Bangka Belitung", "fdescr":  "Belitung", "ftzone": 7, "flstfl": 0}, 
{"_id": 656, "fnewid":  "VXVRNltnVicBc1EzCDQFN1ElADRRPlM4UDJRfANgW2RUNgM4XWVVZwZhWG4AblQx", "fstate":  "Bangka Belitung", "fdescr":  "Belitung Timur", "ftzone": 7, "flstfl": 0}, 
{"_id": 657, "fnewid":  "CioCZQk1AHFQIlQ2CTUKOVMnADQAbw5lAmBWe1AzXmFbOVdsW2NTYVA3VmAJZwBl", "fstate":  "Bangka Belitung", "fdescr":  "Pangkalpinang Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 675, "fnewid":  "CytQNw4yUyJbKVc1CzUBMAdzVmIEa1U%2BVzUNIFU2CzRRM1BrXGRWZAptBTNdM1I3", "fstate":  "Banten", "fdescr":  "Cilegon Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 676, "fnewid":  "UnIHYFpmB3YGdABiCTcKOFAkUGRQPwdsA2FQfVs4XmFTMQI5WmIGNARjAjQJZ1Qx", "fstate":  "Banten", "fdescr":  "Serang Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 677, "fnewid":  "BSVVMgs3USACcApoDDJUZ1ElAzcHaANoUjAEKVEyW2RaOAw3DTVWZAFmUGYJZ104", "fstate":  "Banten", "fdescr":  "Tangerang Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 678, "fnewid":  "ACBTNAs3A3IAcgJgCTdTbwF1ATUDbFM4AGJVeFU2AD9XNVFqCzNSYFA3ADYJZwFk", "fstate":  "Banten", "fdescr":  "Tangerang Selatan Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 671, "fnewid":  "CipQNwk1AXBbKVQ2DzFRZAJ2UWVWOVQ%2FA2EBLFQ3CjVWNAc8CDAGNANkUmQNY1I3", "fstate":  "Banten", "fdescr":  "Lebak", "ftzone": 7, "flstfl": 0}, 
{"_id": 672, "fnewid":  "ASEDZAk1A3JUJlAyWmQBNwJ2Cj5VOg9kVjRVeAZlAD9WNAw3DjZVZ1UyAzUOYARh", "fstate":  "Banten", "fdescr":  "Pandeglang", "ftzone": 7, "flstfl": 0}, 
{"_id": 673, "fnewid":  "CipWMV1hBHVXJQVnW2VUYwVxUGQDbFc8A2FQfVMwWWYAYgA7DzdRYwdgAjRcMlQx", "fstate":  "Banten", "fdescr":  "Serang", "ftzone": 7, "flstfl": 0}, 
{"_id": 674, "fnewid":  "AiJRNltnB3ZUJgBiW2VWZgVxBjIGaQZtDW8GKwNgDzACYAw3WmJTYQdgV2EKZANm", "fstate":  "Banten", "fdescr":  "Tangerang", "ftzone": 7, "flstfl": 0}, 
{"_id": 626, "fnewid":  "AiJYPwg0VyZTIQtpCDNQYlcjV2MCbQVuUDJVeAFiDTJXNQA7DjYFN1I1UGZbNFA9", "fstate":  "Bengkulu", "fdescr":  "Bengkulu Selatan", "ftzone": 7, "flstfl": 0}, 
{"_id": 627, "fnewid":  "BCRRNlpmUSBWJAZkCTIKOVQgBDBVOlM4BWcHKlAzCDdWNFVuCzNVZwJlU2UJZgFs", "fstate":  "Bengkulu", "fdescr":  "Bengkulu Tengah", "ftzone": 7, "flstfl": 0}, 
{"_id": 628, "fnewid":  "CioHYF5iVSRQIgJgDDcKNlMnCj5SPQ9kDW8ALQBjXGMCYAM4WWEOPFUyBDJaNQFs", "fstate":  "Bengkulu", "fdescr":  "Bengkulu Utara", "ftzone": 7, "flstfl": 0}, 
{"_id": 629, "fnewid":  "CipUMwg0UCFRI1AyCjFRbFElBTEDbFA7AWNRfFMwXWJWNAc8CjICMAJlBTMBblU4", "fstate":  "Bengkulu", "fdescr":  "Kaur", "ftzone": 7, "flstfl": 0}, 
{"_id": 630, "fnewid":  "UHBVMlllUiNUJlc1CDJWYlAkBjJQP1c8VTcBLANgXWIGZAc8WmIFNwJlUWcLZFc6", "fstate":  "Bengkulu", "fdescr":  "Kepahiang", "ftzone": 7, "flstfl": 0}, 
{"_id": 635, "fnewid":  "VnZRNgwwVyZbKVc1WWNXZgx4BTEBbgNoAWMEKVQ3DzBTMVZtATlSYAFmVGIKZV0w", "fstate":  "Bengkulu", "fdescr":  "Bengkulu Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 631, "fnewid":  "ASEHYF1hVyZSIAtpADpTZgB0BzNXOFQ%2FAGJVeANgXWJRM1JpDjZSYFE2UmRbNARp", "fstate":  "Bengkulu", "fdescr":  "Lebong", "ftzone": 7, "flstfl": 0}, 
{"_id": 632, "fnewid":  "UXEFYg0xUCECcFMxCzEHMQF1ADQHaAdsBWcDLlo5XmFSMFBrDzcCMAViUmQMYwBt", "fstate":  "Bengkulu", "fdescr":  "Muko-Muko", "ftzone": 7, "flstfl": 0}, 
{"_id": 633, "fnewid":  "CysAZwk1VidbKQFjXmRQZwVxCj4CbVA7AGIBLFIxCDdWNFdsADgDMVUyUWcKZQdq", "fstate":  "Bengkulu", "fdescr":  "Rejanglebong", "ftzone": 7, "flstfl": 0}, 
{"_id": 634, "fnewid":  "AyNQN1xgA3ICcFEzADoDMwRwBzNWOQJpUTNXegFiXmFSMFFqDDQGNAViBTNcMwFs", "fstate":  "Bengkulu", "fdescr":  "Seluma", "ftzone": 7, "flstfl": 0}, 
{"_id": 667, "fnewid":  "AiIFYl5iBHVWJAFjXmELOAVxV2MHaANoDG5QfVs4CTZTMVZtDjYFN1I0WGoMYgRh", "fstate":  "DKI Jakarta", "fdescr":  "Jakarta Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 947, "fnewid":  "BycEYws3XSwBc1A9WmdTYFAkAzcFagZtVzVSf1EyDDNSMAM4XGRUZgBnBzEPYF0w", "fstate":  "Gorontalo", "fdescr":  "Boalemo", "ftzone": 8, "flstfl": 0}, 
{"_id": 948, "fnewid":  "CytVMg4yUSBUJgdqWWQEOA15ADQDbANoUDIALQBjAT5XNQc8DzcFNwZhBDJcM1Y7", "fstate":  "Gorontalo", "fdescr":  "Bonebolango", "ftzone": 8, "flstfl": 0}, 
{"_id": 949, "fnewid":  "CipZPlxgUSAGdApnWmcCPwdzV2NXOARvDW9XegdkWmVTMQw3CTEDMQJlAzVdMgBt", "fstate":  "Gorontalo", "fdescr":  "Gorontalo", "ftzone": 8, "flstfl": 0}, 
{"_id": 950, "fnewid":  "ACACZQs3B3ZQIgRpXWFXYwJ2BDBVOg9kDG4GK1o5XGNQMg02XGQCMAFmBTMOYQBt", "fstate":  "Gorontalo", "fdescr":  "Gorontalo Utara", "ftzone": 8, "flstfl": 0}, 
{"_id": 952, "fnewid":  "BydRNg4yUSBbKVY7XGAGMFQgUGQDbANoB2UALVc0DjFaOAY9DjZVZ1E2BDJaNVM%2B", "fstate":  "Gorontalo", "fdescr":  "Gorontalo Kota", "ftzone": 8, "flstfl": 0}, 
{"_id": 951, "fnewid":  "BSVSNQs3AHEBc1E8DTFQZVElBTEBbgJpVjRVeAdkDTIFZ1dsDTVUZlUyAzVeMVY7", "fstate":  "Gorontalo", "fdescr":  "Pohuwato", "ftzone": 8, "flstfl": 0}, 
{"_id": 599, "fnewid":  "UHAEYw4yAHFXJQVkCTkBPAdzUGRWOVM4UDJWe1Q3DzBTMQc8CzMAMlA3WW8JZ1Q6", "fstate":  "Jambi", "fdescr":  "Batanghari", "ftzone": 7, "flstfl": 0}, 
{"_id": 600, "fnewid":  "VnZRNgwwBHVSIFQ2DjcANFAkATVXOAVuAmANIFMwCjUCYAY9ATlSYAptU2VcMlM9", "fstate":  "Jambi", "fdescr":  "Bungo", "ftzone": 7, "flstfl": 0}, 
{"_id": 601, "fnewid":  "ACBTNAk1VyZSIARmDzYGMwN3BzNQPw5lVTcFKFs4XmEBYw02CzNTYQdgWG4NY1U7", "fstate":  "Jambi", "fdescr":  "Kerinci", "ftzone": 7, "flstfl": 0}, 
{"_id": 608, "fnewid":  "VnYCZQE9B3ZRIwVnAThRbQdzAjYCbVI5DG5QfVQ3CTYGZFBrCjJRYwBnAjQPYQBu", "fstate":  "Jambi", "fdescr":  "Jambi Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 609, "fnewid":  "UnJYP1pmUCFWJApoCzJRbAJ2BzNXOAdsBWdXelAzCzRTMQM4CTFSYAViVmANYwNt", "fstate":  "Jambi", "fdescr":  "Sungai Penuh Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 602, "fnewid":  "VXUAZwg0VidVJ1EzW2IHMQx4AjZVOlQ%2FAGIHKgdkWWZRM1BrDDRUZgNkWW8KZARq", "fstate":  "Jambi", "fdescr":  "Merangin", "ftzone": 7, "flstfl": 0}, 
{"_id": 603, "fnewid":  "VnZZPg0xVyYHdQZkDjdXYFcjBDBXOAFqUjAEKVEyCTYBY1VuDDRTYQdgBDJZNwBu", "fstate":  "Jambi", "fdescr":  "Muarojambi", "ftzone": 7, "flstfl": 0}, 
{"_id": 604, "fnewid":  "AiJTNFtnUiNQIgJgCTAGNgZyATVXOAVuBmQGK1U2XGMFZwY9CjJVZwJlBDIIZlI8", "fstate":  "Jambi", "fdescr":  "Sarolangun", "ftzone": 7, "flstfl": 0}, 
{"_id": 605, "fnewid":  "BSVQNwk1UiNQIlAyDjdWZwB0VGBQP1M4A2FRfFY1AT5aOA02XmYAMgdgVGILZQRq", "fstate":  "Jambi", "fdescr":  "Tanjungjabung Barat", "ftzone": 7, "flstfl": 0}, 
{"_id": 606, "fnewid":  "BycHYFllUSABc1c1XGVUZgx4UWUEawdsUDIALVU2W2RTMQw3WmIENlUyWG4JZ1Q6", "fstate":  "Jambi", "fdescr":  "Tanjungjabung Timur", "ftzone": 7, "flstfl": 0}, 
{"_id": 607, "fnewid":  "AiJWMQE9A3IAcgFjXWQKOQZyBDBVOlU%2BAGIFKABjXWJXNQ02CjIGNAFmBDJdMwZo", "fstate":  "Jambi", "fdescr":  "Tebo", "ftzone": 7, "flstfl": 0}, 
{"_id": 679, "fnewid":  "ACAEYwg0BncBcwBiW2UFOAZyVGANYlQ%2FVzUNIFo5CzRUNgQ%2FXWVTYVYxVGIIZlwy", "fstate":  "Jawa Barat", "fdescr":  "Bandung", "ftzone": 7, "flstfl": 0}, 
{"_id": 680, "fnewid":  "VXUDZAg0BHVTIVEzXG0GMlAkBTFXOA5lAmAHKlY1XmEAYldsCzMHNQNkBzFdMwFv", "fstate":  "Jawa Barat", "fdescr":  "Bandung Barat", "ftzone": 7, "flstfl": 0}, 
{"_id": 681, "fnewid":  "UnIAZ1llAHFSIApoDD1XYgB0AzcDbABrAGIBLFs4XmFSMFVuDzcENgFmAjQIZlA%2B", "fstate":  "Jawa Barat", "fdescr":  "Bekasi", "ftzone": 7, "flstfl": 0}, 
{"_id": 682, "fnewid":  "ASEAZw4yVidTIVAyXm9QZg15BjJSPVA7UTNSf1Q3WWZSMFBrCjJUZgViAzUJZ1A%2B", "fstate":  "Jawa Barat", "fdescr":  "Bogor", "ftzone": 7, "flstfl": 0}, 
{"_id": 683, "fnewid":  "BiZUM1tnVSQFdwNhCjtRZgx4U2cCbVI5UDIBLABjDTJVN1VuDzcPPQJlWW9cMlI8", "fstate":  "Jawa Barat", "fdescr":  "Ciamis", "ftzone": 7, "flstfl": 0}, 
{"_id": 684, "fnewid":  "VnZYP1llVSRaKFc1XG0KOgx4ADRRPg5lAWMNIANgDzBQMg02W2NTYQViAjReMFU7", "fstate":  "Jawa Barat", "fdescr":  "Cianjur", "ftzone": 7, "flstfl": 0}, 
{"_id": 685, "fnewid":  "BydVMl5iBndXJVY0DTwBMFcjBDBSPQZtDW8BLFEyW2QCYAI5W2MCMARjBDJdMwRq", "fstate":  "Jawa Barat", "fdescr":  "Cirebon", "ftzone": 7, "flstfl": 0}, 
{"_id": 686, "fnewid":  "CipSNV1hUyJUJlQ2CzpWZAN3ATUNYlA7A2EDLlEyDjEFZ1BrDTVVZwNkAjRbNVQ6", "fstate":  "Jawa Barat", "fdescr":  "Garut", "ftzone": 7, "flstfl": 0}, 
{"_id": 687, "fnewid":  "BSVUM1xgUiNRIwVnXG1XZFElU2cAbw9kDG4CLwRnCjVVNwc8DTUHNQNkV2FeMAZo", "fstate":  "Jawa Barat", "fdescr":  "Indramayu", "ftzone": 7, "flstfl": 0}, 
{"_id": 688, "fnewid":  "VnYHYA0xVyZTIQBiCDkAPFQgVGAEa1Q%2FAGJWe1Y1XmEGZFVuCjJWZFE2UWcNY1I8", "fstate":  "Jawa Barat", "fdescr":  "Karawang", "ftzone": 7, "flstfl": 0}, 
{"_id": 697, "fnewid":  "BCQFYg8zXC1XJQZkXW0AM1ElCj4Ab1I5BGZWe1EyW2QHZVVuCDBRYwZhVWNeMFwy", "fstate":  "Jawa Barat", "fdescr":  "Bandung Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 698, "fnewid":  "AiIFYlpmXC1aKFc1Dj5Wagx4V2MCbVU%2BBmQALVEyDjEHZQM4XGRSYFA3UWcPYVA%2B", "fstate":  "Jawa Barat", "fdescr":  "Banjar Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 699, "fnewid":  "AyNWMQk1AHFSIFY0W2sKNwN3ATVQPwVuBWcDLls4CDdSMFBrDTUHNVYxVGJaNAFv", "fstate":  "Jawa Barat", "fdescr":  "Bekasi Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 700, "fnewid":  "UXFQNw8zVyZVJwVmWWAFMQJ2VGBWOVI5DW8FKABjAD8FZ1FqCjJVZ1UyBTNaNAdp", "fstate":  "Jawa Barat", "fdescr":  "Bogor Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 701, "fnewid":  "BiZSNQ0xAXACcFY1XGVTZgx4AzcNYlQ%2FVTcHKgZlXWJTMVdsDzcENgNkVWMJZ1A%2B", "fstate":  "Jawa Barat", "fdescr":  "Cimahi Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 702, "fnewid":  "UHBVMlpmVSQCcAFiW2IGMAJ2V2MNYg9kVjRQfVEyXmEGZFZtADhVZwBnUWcLZVE%2F", "fstate":  "Jawa Barat", "fdescr":  "Cirebon Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 703, "fnewid":  "UXEDZFpmAXAHdQRnDjcGMVQgADRSPQJpVTcDLlAzDjFQMgI5CTEDMVI1UGYOYFM9", "fstate":  "Jawa Barat", "fdescr":  "Depok Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 704, "fnewid":  "BCQCZQ0xUSABcwNgXWQKOgN3ADQAb1U%2BBmRRfAFiAD9RMww3XGQCMARjAjQAbgRq", "fstate":  "Jawa Barat", "fdescr":  "Sukabumi Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 705, "fnewid":  "BydTNAA8BHVaKAFiW2JTYgJ2ATUDbAdsAWMEKVIxWmVbOQE6ADhWZAJlBTMJZ1M9", "fstate":  "Jawa Barat", "fdescr":  "Tasikmalaya Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 689, "fnewid":  "BSVQNw8zVCUGdAtpCzpTblMnCz8MY1I5VTcBLFMwCzQHZVVuDTUAMgdgBzENY1I8", "fstate":  "Jawa Barat", "fdescr":  "Kuningan", "ftzone": 7, "flstfl": 0}, 
{"_id": 690, "fnewid":  "ASEFYgg0VCVXJQBiCDhTZwdzUGQNYlU%2BDG4ALQNgXGMFZwQ%2FCTEAMlI1VmBZN1wy", "fstate":  "Jawa Barat", "fdescr":  "Majalengka", "ftzone": 7, "flstfl": 0}, 
{"_id": 696, "fnewid":  "ASEDZAg0AXBVJwtpDj4GNA15ATVVOlI5AGJXegdkWmVSMAU%2BXGQCMFI1AjQKZF0z", "fstate":  "Jawa Barat", "fdescr":  "Pangandaran", "ftzone": 7, "flstfl": 0}, 
{"_id": 691, "fnewid":  "UnJSNVpmVSRXJQBiW2sDNgN3Cz9VOlI5VTcALVEyXGMAYlFqDzdWZFI1VWMAblM9", "fstate":  "Jawa Barat", "fdescr":  "Purwakarta", "ftzone": 7, "flstfl": 0}, 
{"_id": 692, "fnewid":  "AiJZPg4yAHFUJlY0Xm4KPFMnBDBWOQNoBWcFKARnXWJRMwE6DTUHNVI1UmRcMgZo", "fstate":  "Jawa Barat", "fdescr":  "Subang", "ftzone": 7, "flstfl": 0}, 
{"_id": 693, "fnewid":  "ACAAZwo2UiMHdVAyDT1UY1YiBzNWOVM4B2UCL1o5DDNRMww3CTECMAFmAjQIZlY4", "fstate":  "Jawa Barat", "fdescr":  "Sukabumi", "ftzone": 7, "flstfl": 0}, 
{"_id": 694, "fnewid":  "CytVMlpmXSwGdAJgWWlUZAdzCz9RPgRvVjQMIVU2DzAHZVJpDTUCMFUyVWNcMlA%2B", "fstate":  "Jawa Barat", "fdescr":  "Sumedang", "ftzone": 7, "flstfl": 0}, 
{"_id": 695, "fnewid":  "ASFXMAo2USAHdVY0Xm5QYVMnUWUAbwRvDW8FKFMwWWZQMgc8XWVSYFA3VWMPYQBu", "fstate":  "Jawa Barat", "fdescr":  "Tasikmalaya", "ftzone": 7, "flstfl": 0}, 
{"_id": 706, "fnewid":  "VXVYP1pmXC1UJlMwCjMKOAJ2ADRXOFM4UDJXegRnDjECYAU%2BADgCMFcwVGIAblwy", "fstate":  "Jawa Tengah", "fdescr":  "Banjarnegara", "ftzone": 7, "flstfl": 0}, 
{"_id": 707, "fnewid":  "CipVMg0xAHFUJgdkXmcAM1cjU2dQPwVuBmQALVIxXmFaOAc8W2MBM1E2BDINYwFv", "fstate":  "Jawa Tengah", "fdescr":  "Banyumas", "ftzone": 7, "flstfl": 0}, 
{"_id": 708, "fnewid":  "AyNQN1pmXSwHdVMwXWQAPARwU2cBbgRvAGIMIVMwCzQGZA02ADhSYFA3UWcBb1wy", "fstate":  "Jawa Tengah", "fdescr":  "Batang", "ftzone": 7, "flstfl": 0}, 
{"_id": 709, "fnewid":  "UHBQN15iUCFWJAJhXmcHOgZyBjINYgJpVzUNIFAzAT4AYgQ%2FCTEHNQFmVmBZN1E%2F", "fstate":  "Jawa Tengah", "fdescr":  "Blora", "ftzone": 7, "flstfl": 0}, 
{"_id": 710, "fnewid":  "AyMHYA8zUiNVJwZlXGQDNw15VmINYgJpB2UDLls4XGNbOQY9DTVSYAptAzVeMF0z", "fstate":  "Jawa Tengah", "fdescr":  "Boyolali", "ftzone": 7, "flstfl": 0}, 
{"_id": 711, "fnewid":  "V3dSNQo2A3IAcgBjXWVWY1ElU2cCbVA7BmRWe1AzCzRSMFZtCTEAMlYxWW8MYl0z", "fstate":  "Jawa Tengah", "fdescr":  "Brebes", "ftzone": 7, "flstfl": 0}, 
{"_id": 712, "fnewid":  "AiJVMgk1VyZWJAVmCTEGMFElBjINYgNoBGYMIQNgDDNSMAc8CTEFNwFmUWcLZVY4", "fstate":  "Jawa Tengah", "fdescr":  "Cilacap", "ftzone": 7, "flstfl": 0}, 
{"_id": 713, "fnewid":  "BSVRNlpmBHUGdAppCjIDNAJ2VmIAbwJpBWdXelc0CzRTMVdsCzMOPAdgBzELZVY4", "fstate":  "Jawa Tengah", "fdescr":  "Demak", "ftzone": 7, "flstfl": 0}, 
{"_id": 714, "fnewid":  "ASEDZAE9BncBcwJhXGQENAF1BjINYg5lUTMCL1AzW2QAYgE6CTEGNAZhV2FZN1wy", "fstate":  "Jawa Tengah", "fdescr":  "Grobogan", "ftzone": 7, "flstfl": 0}, 
{"_id": 715, "fnewid":  "BydRNlpmVSRUJlMwCDAAMQJ2BjIDbAVuAWMEKVY1DDMCYAc8CTFWZAptADYJZ1Q6", "fstate":  "Jawa Tengah", "fdescr":  "Jepara", "ftzone": 7, "flstfl": 0}, 
{"_id": 716, "fnewid":  "UHBXMFllUCFQIgZlXGQHNQB0VGBVOlI5VzVSf1EyCjVbOVdsCzMPPVE2BTMMYlQ6", "fstate":  "Jawa Tengah", "fdescr":  "Karanganyar", "ftzone": 7, "flstfl": 0}, 
{"_id": 717, "fnewid":  "UnIAZ1tnVyZUJgNgWmJQYwN3V2NSPQJpBmQEKQRnDDNTMQE6DzdWZFUyAjRcMgNt", "fstate":  "Jawa Tengah", "fdescr":  "Kebumen", "ftzone": 7, "flstfl": 0}, 
{"_id": 718, "fnewid":  "BycDZA4yBndQIgFiW2MKNgB0U2cFagBrDG5SfwdkDTIGZFdsATlTYQBnBzFbNQFv", "fstate":  "Jawa Tengah", "fdescr":  "Kendal", "ftzone": 7, "flstfl": 0}, 
{"_id": 719, "fnewid":  "ACBYP1pmBHUGdANgCDBWa1AkAzcFagFqAGJWewNgXmFTMQI5DTUFNwZhV2FdM1wy", "fstate":  "Jawa Tengah", "fdescr":  "Klaten", "ftzone": 7, "flstfl": 0}, 
{"_id": 736, "fnewid":  "BCRYPwo2A3ICcFY1CTNWZFYiV2NVOgBrAGJXegdkAD9UNgA7DjYFNwJlAzUPYQFv", "fstate":  "Jawa Tengah", "fdescr":  "Magelang Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 737, "fnewid":  "ACBQNwo2UyJRI1AzCDICMVYiUGQAbwdsAmAFKFU2AD9aOAQ%2FDTUFN1cwUWcAbgZo", "fstate":  "Jawa Tengah", "fdescr":  "Pekalongan Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 738, "fnewid":  "ASFQN1pmUyJVJwNgWmBQbAVxCz9VOgBrBmRRfFAzCDdXNQY9CzMBM1YxBDJZNwdp", "fstate":  "Jawa Tengah", "fdescr":  "Salatiga Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 735, "fnewid":  "ASFZPg0xXSwFdwtoWmAKO1MnBjICbQBrAmBRfFY1DjEBYwM4DzcAMgRjAjQMYgdp", "fstate":  "Jawa Tengah", "fdescr":  "Semarang Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 739, "fnewid":  "UnIFYlxgA3JXJQFiATsKNwx4ATUNYlA7VzUNIFEyAT4AYgI5CzMOPAJlWW8NY1Y4", "fstate":  "Jawa Tengah", "fdescr":  "Surakarta Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 740, "fnewid":  "ASEDZFllUyJbKVc0XWAGMgJ2VmINYlI5DW9WewRnCTZUNlZtATlUZgNkVGIMYgBu", "fstate":  "Jawa Tengah", "fdescr":  "Tegal Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 720, "fnewid":  "AiJRNlxgVidTIQVmDDcEMFMnUWVSPQZtUDJVeFIxXGMCYFBrDTVTYQtsUGYLZVQ6", "fstate":  "Jawa Tengah", "fdescr":  "Kudus", "ftzone": 7, "flstfl": 0}, 
{"_id": 721, "fnewid":  "ACBSNVxgVicAcgRnDDcFMA15BjIBblI5B2VSf1Y1CjVSMFZtXmYFNwViVGJeMAZo", "fstate":  "Jawa Tengah", "fdescr":  "Magelang", "ftzone": 7, "flstfl": 0}, 
{"_id": 722, "fnewid":  "UXEDZA4yVyYGdABjXGcHMVAkV2NVOlc8VjRQfVs4WmVSMA02ATlUZgViAzVeMAZo", "fstate":  "Jawa Tengah", "fdescr":  "Pati", "ftzone": 7, "flstfl": 0}, 
{"_id": 723, "fnewid":  "BCRYPwE9UiNTIVY1ADsGMQ15V2MGaVQ%2FUjAMIVs4XGNXNQw3XGQAMlA3WG4OYANt", "fstate":  "Jawa Tengah", "fdescr":  "Pekalongan", "ftzone": 7, "flstfl": 0}, 
{"_id": 724, "fnewid":  "BSVTNAg0VSQGdAVmADsAMAZyBzMAb1c8BGZXegBjCjVRMwQ%2FDTUDMQRjV2FbNVA%2B", "fstate":  "Jawa Tengah", "fdescr":  "Pemalang", "ftzone": 7, "flstfl": 0}, 
{"_id": 725, "fnewid":  "VXUCZVxgVyZQIgVmWWIDMlMnAzcBbgZtB2UFKAFiCDdSMAU%2BWmJSYAZhVmAOYFY4", "fstate":  "Jawa Tengah", "fdescr":  "Purbalingga", "ftzone": 7, "flstfl": 0}, 
{"_id": 726, "fnewid":  "ASEDZFpmUyJUJlEyCjEHNQRwBzMHaAdsVjRVeFU2CDcBYwM4CjJRYwdgV2EBbwBu", "fstate":  "Jawa Tengah", "fdescr":  "Purworejo", "ftzone": 7, "flstfl": 0}, 
{"_id": 727, "fnewid":  "AiJVMg4yXC1XJVEyCjEKOQZyAzcHaA9kDW8BLAdkDDNaOFFqWWEGNAtsWG5eMABu", "fstate":  "Jawa Tengah", "fdescr":  "Rembang", "ftzone": 7, "flstfl": 0}, 
{"_id": 728, "fnewid":  "V3dSNV1hVSRRIwNgDzQKNgdzBjJQP1Q%2FDW8EKVIxXmECYFdsATkOPAdgBDILZQZo", "fstate":  "Jawa Tengah", "fdescr":  "Semarang", "ftzone": 7, "flstfl": 0}, 
{"_id": 729, "fnewid":  "AyNRNl1hUiMHdQtoWmEHOlQgADQFag5lVjQALQBjW2RbOQE6CTFWZFYxADYNYwRq", "fstate":  "Jawa Tengah", "fdescr":  "Sragen", "ftzone": 7, "flstfl": 0}, 
{"_id": 730, "fnewid":  "CipVMlxgUyICcAVmXWdQZAx4VGBRPgBrVTdVeFAzCDdSMFVuXWUDMQFmBDILZVc5", "fstate":  "Jawa Tengah", "fdescr":  "Sukoharjo", "ftzone": 7, "flstfl": 0}, 
{"_id": 731, "fnewid":  "ASFQN1pmVidaKFEyXGYHMlAkCz8FagZtUTMDLlo5DTICYAA7WmIFNwptVGIPYVU7", "fstate":  "Jawa Tengah", "fdescr":  "Tegal", "ftzone": 7, "flstfl": 0}, 
{"_id": 732, "fnewid":  "VnZSNVtnAXBQIlY1DDZTZQB0VGBSPQBrVjQMIVIxDDNVN1VuDDQOPAZhVWMPYVY4", "fstate":  "Jawa Tengah", "fdescr":  "Temanggung", "ftzone": 7, "flstfl": 0}, 
{"_id": 733, "fnewid":  "BiZYPw0xUyIBc1Q3ATtWYVMnV2MEawZtDG4CLwRnDzBUNgY9W2NRYwBnUmRcMgNt", "fstate":  "Jawa Tengah", "fdescr":  "Wonogiri", "ftzone": 7, "flstfl": 0}, 
{"_id": 734, "fnewid":  "UnJSNQwwVidTIQJhDjRWZgRwVmIMY1M4AGJQfVQ3DDNQMgY9XGQOPAptV2EIZlQ6", "fstate":  "Jawa Tengah", "fdescr":  "Wonosobo", "ftzone": 7, "flstfl": 0}, 
{"_id": 741, "fnewid":  "BCQFYgg0VyYGdFAzCDVQZQJ2VGABblI5UjACL1Q3WmVVNwU%2BXGRVZwRjWW8MYlI8", "fstate":  "Jawa Timur", "fdescr":  "Bangkalan", "ftzone": 7, "flstfl": 0}, 
{"_id": 742, "fnewid":  "VnYCZVtnAXBTIVQ3CzYBN1AkCj5XOARvDW9VeFEyCTZTMQU%2BDTUCMFcwBzENYwZo", "fstate":  "Jawa Timur", "fdescr":  "Banyuwangi", "ftzone": 7, "flstfl": 0}, 
{"_id": 743, "fnewid":  "CytVMlxgB3ZbKQNgDzJUY1YiCz8Ab1U%2BDW8BLFAzXGMAYgA7DjZVZ1cwBzEAbl0z", "fstate":  "Jawa Timur", "fdescr":  "Blitar", "ftzone": 7, "flstfl": 0}, 
{"_id": 744, "fnewid":  "CytSNQwwB3YGdFQ3CzZXZwF1BDAMY1Q%2FUDIALVIxWWZTMVBrATlWZABnVWNdMwBu", "fstate":  "Jawa Timur", "fdescr":  "Bojonegoro", "ftzone": 7, "flstfl": 0}, 
{"_id": 745, "fnewid":  "BiZYP1xgXC0BcwZlDzJUZVcjBzNXOABrUDIGK1EyCzRTMQI5CTEFNwRjBTMOYF0z", "fstate":  "Jawa Timur", "fdescr":  "Bondowoso", "ftzone": 7, "flstfl": 0}, 
{"_id": 746, "fnewid":  "BSUHYFxgXC0CcAJhDjNWZFYiCj4Falc8DW8GKwFiDzAGZAE6CTFRYwViVGIJZwBu", "fstate":  "Jawa Timur", "fdescr":  "Gresik", "ftzone": 7, "flstfl": 0}, 
{"_id": 747, "fnewid":  "AiJUM11hAXBVJ1AzWWQGNQZyBTENYg9kDW8MIVAzXGMFZ1ZtXWVRYwZhBTMJZ1I8", "fstate":  "Jawa Timur", "fdescr":  "Jember", "ftzone": 7, "flstfl": 0}, 
{"_id": 748, "fnewid":  "VXVWMQ4yVSRVJwppCTQGOgdzADRVOgZtVzUNIAZlXGNSMFBrADhVZwNkV2EBb1c5", "fstate":  "Jawa Timur", "fdescr":  "Jombang", "ftzone": 7, "flstfl": 0}, 
{"_id": 749, "fnewid":  "BSVQN1xgXSxXJVMwDDFXalElU2cGaQJpVzUEKQNgAD9WNAQ%2FDzcDMQBnAjQMYlY4", "fstate":  "Jawa Timur", "fdescr":  "Kediri", "ftzone": 7, "flstfl": 0}, 
{"_id": 771, "fnewid":  "AiJZPg0xBndaKAJhCTcHMlAkUWVQPw5lDW8MIVo5CjUGZFVuDzdVZ1A3BzFcMlU7", "fstate":  "Jawa Timur", "fdescr":  "Batu Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 772, "fnewid":  "UXFUMwo2VSRWJFEyDzEEMgZyUGRSPQRvUDJQfVEyDjFWNFBrW2NVZ1UyBTMKZFA%2B", "fstate":  "Jawa Timur", "fdescr":  "Blitar Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 773, "fnewid":  "CipVMgg0VyYGdFAzXWNRZlQgATVVOgZtBmRXegZlXGMHZQM4XGQDMVcwVmAAblA%2B", "fstate":  "Jawa Timur", "fdescr":  "Kediri Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 774, "fnewid":  "VXVQN1llUyJVJwRnDzFXZ1QgAzcEawRvVTdVeFEyCTYAYg02W2NSYFUyU2UPYVU7", "fstate":  "Jawa Timur", "fdescr":  "Madiun Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 775, "fnewid":  "UnJXMAA8UiNaKFAzAD5RYAJ2AzcMYwRvVzUDLgZlAT4FZwM4XWVRY1E2VWNZNwRq", "fstate":  "Jawa Timur", "fdescr":  "Malang Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 776, "fnewid":  "UHAHYA0xAHFTIQdkCTdUZgZyAzcBblU%2BAWMBLFs4CDdQMldsWWEHNVE2BTNaNFM9", "fstate":  "Jawa Timur", "fdescr":  "Mojokerto Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 777, "fnewid":  "AyMFYgE9A3ICcFY1WWdWZQB0ADRVOgVuUTMALVMwAT5RM1FqDDRUZgFmV2EPYVE%2F", "fstate":  "Jawa Timur", "fdescr":  "Pasuruan Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 778, "fnewid":  "BycFYgA8VidVJ1AzXWNTbwB0BDABbgZtDW8MIVAzXmFXNQE6XWUBMwNkUWcJZwFv", "fstate":  "Jawa Timur", "fdescr":  "Probolinggo Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 770, "fnewid":  "CipXMAk1UyJaKAppDjAANAVxATUBbgNoVzUDLlo5CzRXNQE6CDBUZgJlAjQNYwNt", "fstate":  "Jawa Timur", "fdescr":  "Surabaya Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 750, "fnewid":  "CipYP1llAXAAclEyADwGMgN3ATVVOgdsUDICL1Y1XmFUNgQ%2FADgPPVI1AjRdMwRq", "fstate":  "Jawa Timur", "fdescr":  "Lamongan", "ftzone": 7, "flstfl": 0}, 
{"_id": 751, "fnewid":  "ASEFYgwwVyZUJgdkADwCNw15ADRSPVM4DG4ALQBjW2RXNVJpXWUGNABnBDJbNVQ6", "fstate":  "Jawa Timur", "fdescr":  "Lumajang", "ftzone": 7, "flstfl": 0}, 
{"_id": 752, "fnewid":  "UXEAZwg0XSxSIFMwADxUYlcjBTFWOVQ%2FAmBXegRnAT4FZwQ%2FWWEHNQtsWW8Bb1A%2B", "fstate":  "Jawa Timur", "fdescr":  "Madiun", "ftzone": 7, "flstfl": 0}, 
{"_id": 753, "fnewid":  "AyMDZFllAHFWJANgWmYBNlElVmINYlc8UjACL1o5DTJVNwU%2BWWEGNAZhUWdZNwZo", "fstate":  "Jawa Timur", "fdescr":  "Magetan", "ftzone": 7, "flstfl": 0}, 
{"_id": 754, "fnewid":  "UXEAZwg0BHUCcAZlCjYGNgF1BjIBbgNoUjADLlIxDDMCYAc8DzcBM1YxADZZN1Q6", "fstate":  "Jawa Timur", "fdescr":  "Malang", "ftzone": 7, "flstfl": 0}, 
{"_id": 755, "fnewid":  "UnJVMgg0USBbKVEyCzcKO1ElBDBSPQBrUTMDLlQ3AD9QMgE6CTEOPAtsAzVcMlQ6", "fstate":  "Jawa Timur", "fdescr":  "Mojokerto", "ftzone": 7, "flstfl": 0}, 
{"_id": 756, "fnewid":  "BiZXMFllBHUAcgFiADxUZlAkBzNQP1U%2BB2VVeFs4CTZaOAE6DjZWZAViV2EIZgRq", "fstate":  "Jawa Timur", "fdescr":  "Nganjuk", "ftzone": 7, "flstfl": 0}, 
{"_id": 757, "fnewid":  "CipXMAE9XC1SIFY1AT0GNVcjUGQAbwJpAWMDLlY1DzBRM1FqXmYCMFYxBzEIZgFv", "fstate":  "Jawa Timur", "fdescr":  "Ngawi", "ftzone": 7, "flstfl": 0}, 
{"_id": 758, "fnewid":  "AyMCZQA8UCFTIQtoWmYLNwZyBDADbA9kAmAALVEyCzRRM1VuCjJUZlE2VGIKZFI8", "fstate":  "Jawa Timur", "fdescr":  "Pacitan", "ftzone": 7, "flstfl": 0}, 
{"_id": 759, "fnewid":  "BSVWMQ0xUiNRI1Y1CjYEOVQgCj4Eaw5lUTMGK1AzXmEFZ1FqCjIPPQNkU2VdMwFv", "fstate":  "Jawa Timur", "fdescr":  "Pamekasan", "ftzone": 7, "flstfl": 0}, 
{"_id": 760, "fnewid":  "BiZUMwE9XC1bKQJhCDcGMgB0BjJQP1A7B2VVeABjCTZXNVVuXWUCMFA3WW9eMFQ6", "fstate":  "Jawa Timur", "fdescr":  "Pasuruan", "ftzone": 7, "flstfl": 0}, 
{"_id": 761, "fnewid":  "BSVWMQwwVicHdQRnCDcEMQ15UGRRPgdsVjQFKFIxCDdXNVZtW2MPPQFmAzUMYlI8", "fstate":  "Jawa Timur", "fdescr":  "Ponorogo", "ftzone": 7, "flstfl": 0}, 
{"_id": 762, "fnewid":  "BydYPw8zB3YBcwNgAD8HMVQgADRSPQ9kAmAFKFIxDjEFZ1VuATlRY1YxAjReMABu", "fstate":  "Jawa Timur", "fdescr":  "Probolinggo", "ftzone": 7, "flstfl": 0}, 
{"_id": 763, "fnewid":  "UXFQNws3XSxSIAppW2QLPAN3ADRWOQ5lAmBWe1AzCzRXNQY9XmYENlI1WW9dMwdp", "fstate":  "Jawa Timur", "fdescr":  "Sampang", "ftzone": 7, "flstfl": 0}, 
{"_id": 764, "fnewid":  "ASECZQo2BndaKARnDDNTYw15BTEEa1Q%2FAmANIFc0XGMFZwc8DTVRY1I1UWdbNQZo", "fstate":  "Jawa Timur", "fdescr":  "Sidoarjo", "ftzone": 7, "flstfl": 0}, 
{"_id": 765, "fnewid":  "V3cCZQ0xVyZXJQFiCTZQYQB0VGABbgBrDW9Sf1Y1XGMBYw02XGQPPQZhUWcAblI8", "fstate":  "Jawa Timur", "fdescr":  "Situbondo", "ftzone": 7, "flstfl": 0}, 
{"_id": 766, "fnewid":  "CytZPg0xVidTIVQ3W2QFN1AkBjINYgZtAGIALVo5CDcAYldsXGRUZlUyVWMIZlI8", "fstate":  "Jawa Timur", "fdescr":  "Sumenep", "ftzone": 7, "flstfl": 0}, 
{"_id": 767, "fnewid":  "BiYFYltnUSBVJ1AzXGMCMVYiV2MAbwJpVjRWewdkCDdWNFFqDDRTYVcwADZdM1M9", "fstate":  "Jawa Timur", "fdescr":  "Trenggalek", "ftzone": 7, "flstfl": 0}, 
{"_id": 769, "fnewid":  "CysEYws3BHUFdwZlCjUKN1ElBjJWOQ5lUTNVeFAzCDdVN1JpCTFTYQFmU2UBbwNt", "fstate":  "Jawa Timur", "fdescr":  "Tuban", "ftzone": 7, "flstfl": 0}, 
{"_id": 768, "fnewid":  "CytZPg4yBHVaKARnDTIEOA15BTECbQ5lVTcCLwRnW2RWNA02CzMENgtsVWNcMlA%2B", "fstate":  "Jawa Timur", "fdescr":  "Tulungagung", "ftzone": 7, "flstfl": 0}, 
{"_id": 825, "fnewid":  "BiZSNQ8zXSxRI1M%2FCjFXZg15V2MNYlM4BGZVeANgWWYAYlFqDTUBM1I1VGJaNAdo", "fstate":  "Kalimantan Barat", "fdescr":  "Bengkayang", "ftzone": 7, "flstfl": 0}, 
{"_id": 826, "fnewid":  "UHAEYws3USAGdFE9XmVQYgRwUGQGaQdsUjANIFc0DzAHZVFqCDAAMgJlUWcOYAZp", "fstate":  "Kalimantan Barat", "fdescr":  "Kapuas Hulu", "ftzone": 7, "flstfl": 0}, 
{"_id": 828, "fnewid":  "VXUHYFpmAXAHdQdrCzABPQ15AzdWOQdsDW9XelEyXWIGZAA7CjICMAdgUGZcMgdo", "fstate":  "Kalimantan Barat", "fdescr":  "Kayong Utara", "ftzone": 7, "flstfl": 0}, 
{"_id": 827, "fnewid":  "VnZSNV1hB3YGdFc7CTIEN1ElAjZQPwZtAGJWe1U2DjFVNwM4XmZUZgFmUWcOYAdo", "fstate":  "Kalimantan Barat", "fdescr":  "Ketapang", "ftzone": 7, "flstfl": 0}, 
{"_id": 837, "fnewid":  "AiJWMQk1XSxSIFM%2FATtRYlcjATVWOQ5lBmQHKgRnDzBXNVdsWmJRYwFmAzUBb1E%2B", "fstate":  "Kalimantan Barat", "fdescr":  "Pontianak Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 838, "fnewid":  "ASFWMVpmBHVUJgtnCjAEOFMnATVXOA9kDG4ALVIxWmVRM1ZtADgHNQZhV2EKZANs", "fstate":  "Kalimantan Barat", "fdescr":  "Singkawang Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 829, "fnewid":  "CioDZAk1B3YGdAtnADsHOgRwAzcNYgRvA2EGKwFiWmVTMQQ%2FDjZRYwdgADZcMgRr", "fstate":  "Kalimantan Barat", "fdescr":  "Kuburaya", "ftzone": 7, "flstfl": 0}, 
{"_id": 830, "fnewid":  "BiYHYAA8XC0CcABsDjRTZ1QgAzdXOAdsBWcEKVY1XWIBYwI5WmIDMQptVWMBb1Y5", "fstate":  "Kalimantan Barat", "fdescr":  "Landak", "ftzone": 7, "flstfl": 0}, 
{"_id": 831, "fnewid":  "CysDZFxgUyIFd1M%2FDDYHMlElCj4NYgFqDG4MIVs4XmFaOAM4CjJWZFcwUGYPYVY5", "fstate":  "Kalimantan Barat", "fdescr":  "Melawi", "ftzone": 7, "flstfl": 0}, 
{"_id": 832, "fnewid":  "CysHYAE9A3JVJ1A8XWdTZQRwBDBRPgZtVzUMIVIxDDMBYwc8XmYGNAptU2VdM1Y5", "fstate":  "Kalimantan Barat", "fdescr":  "Pontianak", "ftzone": 7, "flstfl": 0}, 
{"_id": 833, "fnewid":  "BydSNVxgUSBSIApmCTNXYFcjV2NQPwJpBmRVeFMwAD8AYgM4XWVUZgZhWG4KZABv", "fstate":  "Kalimantan Barat", "fdescr":  "Sambas", "ftzone": 7, "flstfl": 0}, 
{"_id": 834, "fnewid":  "V3dVMgE9BHVbKQVpADpUZAN3BzNWOQdsAmAHKgNgW2RSMAw3DzcHNVI1UWdcMlwz", "fstate":  "Kalimantan Barat", "fdescr":  "Sanggau", "ftzone": 7, "flstfl": 0}, 
{"_id": 836, "fnewid":  "AyNRNltnUCFSIAtnDzUENg15UWUGaQRvDW8MIVs4WmUHZQE6DDRRY1cwAzVdM1U6", "fstate":  "Kalimantan Barat", "fdescr":  "Sekadau", "ftzone": 7, "flstfl": 0}, 
{"_id": 835, "fnewid":  "VnYHYAk1UiMFd1A8DzUBMFQgU2cEaw9kUDIFKFY1AD8GZAM4ATkBMwBnVmBcMgdo", "fstate":  "Kalimantan Barat", "fdescr":  "Sintang", "ftzone": 7, "flstfl": 0}, 
{"_id": 853, "fnewid":  "ASFSNQ4yVCVbKQRoDjIGMVMnUWUCbQ9kBWcEKVMwCjVUNgM4CTFUZgZhVmBdM1wz", "fstate":  "Kalimantan Selatan", "fdescr":  "Balangan", "ftzone": 8, "flstfl": 0}, 
{"_id": 854, "fnewid":  "BSVQN1llUSAFdwZqDjJUZFQgUGQFalI5VTdQfQBjCDdVNwc8DDQENlYxWG4LZQZp", "fstate":  "Kalimantan Selatan", "fdescr":  "Banjar", "ftzone": 8, "flstfl": 0}, 
{"_id": 855, "fnewid":  "BSVQNwE9AXAHdQFtCzdUZQJ2ADRSPQZtA2EMIQdkCjUBYwQ%2FADgBMwViBTNeMFA%2F", "fstate":  "Kalimantan Selatan", "fdescr":  "Baritokuala", "ftzone": 8, "flstfl": 0}, 
{"_id": 856, "fnewid":  "UXFTNFllUiMHdQdrCDQENlMnVmIGaVU%2BB2UDLgBjDzBUNldsXWUPPQdgAzVbNQZp", "fstate":  "Kalimantan Selatan", "fdescr":  "Hulusungai Selatan", "ftzone": 8, "flstfl": 0}, 
{"_id": 857, "fnewid":  "BSVTNA8zB3ZSIFQ4WWVXZAdzUGQNYgRvVTdWewZlAT4AYgA7CTEDMQRjBTMAblE%2B", "fstate":  "Kalimantan Selatan", "fdescr":  "Hulusungai Tengah", "ftzone": 8, "flstfl": 0}, 
{"_id": 858, "fnewid":  "BiYEYwg0BHVaKAtnDDBTb1QgBjICbQZtBmQFKABjAT5bOQA7DTUDMQtsVWMKZANs", "fstate":  "Kalimantan Selatan", "fdescr":  "Hulusungai Utara", "ftzone": 8, "flstfl": 0}, 
{"_id": 865, "fnewid":  "CysFYg0xUyJUJgNvCjVUZQdzCj4HaAFqUDJWe1MwWmVbOQQ%2FATlSYFA3VmBdM1Y5", "fstate":  "Kalimantan Selatan", "fdescr":  "Banjarbaru Kota", "ftzone": 8, "flstfl": 0}, 
{"_id": 864, "fnewid":  "BSUEY1pmXSxWJFc7DjELOwJ2BDAFalI5A2EFKFc0CTZQMgw3CjIPPVA3VmAMYlI9", "fstate":  "Kalimantan Selatan", "fdescr":  "Banjarmasin Kota", "ftzone": 8, "flstfl": 0}, 
{"_id": 859, "fnewid":  "ACAFYgo2VCUGdAJuCjZXagF1BTFQPwJpA2EBLARnCjVRM1ZtXGRWZAZhWW9aNABv", "fstate":  "Kalimantan Selatan", "fdescr":  "Kotabaru", "ftzone": 8, "flstfl": 0}, 
{"_id": 860, "fnewid":  "ASFSNVpmUSBTIVc7DjECNgVxBjJSPQBrA2FXegdkCTYHZQc8ADhUZgptVGILZVQ7", "fstate":  "Kalimantan Selatan", "fdescr":  "Tabalong", "ftzone": 8, "flstfl": 0}, 
{"_id": 861, "fnewid":  "VnZTNA8zUyJWJAdrXmFUYQB0BTEGaQZtBmQEKVQ3CDcGZFVuW2NTYQRjUWcMYlc4", "fstate":  "Kalimantan Selatan", "fdescr":  "Tanahbumbu", "ftzone": 8, "flstfl": 0}, 
{"_id": 862, "fnewid":  "BSVWMQo2VyYGdFA8XmEANgN3AzdXOFA7VTdQfVEyDzBbOQM4ATkHNQViVGJeMFU6", "fstate":  "Kalimantan Selatan", "fdescr":  "Tanahlaut", "ftzone": 8, "flstfl": 0}, 
{"_id": 863, "fnewid":  "BycAZ15iUyJaKFQ4XWICNQRwVGBXOAFqBWdQfVo5WWYHZQI5CzNSYABnBDIIZlwz", "fstate":  "Kalimantan Selatan", "fdescr":  "Tapin", "ftzone": 8, "flstfl": 0}, 
{"_id": 839, "fnewid":  "BSVSNQ0xB3YCcFY6DzUDPlQgCj4BblI5VzUNIFMwDDNRMwQ%2FXmZSYANkVmBZN1Q7", "fstate":  "Kalimantan Tengah", "fdescr":  "Barito Selatan", "ftzone": 7, "flstfl": 0}, 
{"_id": 840, "fnewid":  "VnYAZ1pmVSQGdFE9WWQBNQVxVGBVOgZtAGIEKQdkDDNaOAM4DTUBM1UyWW9bNVU6", "fstate":  "Kalimantan Tengah", "fdescr":  "Barito Timur", "ftzone": 7, "flstfl": 0}, 
{"_id": 841, "fnewid":  "AyMAZ1xgUCFQIgRoCjcCN1YiUGRVOgFqVjRRfFIxXGNSMAQ%2FCzNRYwNkUmQIZgZp", "fstate":  "Kalimantan Tengah", "fdescr":  "Barito Utara", "ftzone": 7, "flstfl": 0}, 
{"_id": 842, "fnewid":  "VXUDZAk1VidbKQpmATwLPQZyVmIMY1Q%2FDG5XelQ3AT4HZQM4DzcOPFE2UWcJZ1Q7", "fstate":  "Kalimantan Tengah", "fdescr":  "Gunungmas", "ftzone": 7, "flstfl": 0}, 
{"_id": 843, "fnewid":  "VXUCZV1hVicAclQ4DzIGMQRwVGABbgZtVTdQfVY1DDNRM1JpXmYENgViAzVeMFc4", "fstate":  "Kalimantan Tengah", "fdescr":  "Kapuas", "ftzone": 7, "flstfl": 0}, 
{"_id": 844, "fnewid":  "BSVUMwA8BndWJFM%2FCjcDMwB0AzcMY1M4BWdVeAZlAT5XNQc8XGRSYAFmWW9cMgNs", "fstate":  "Kalimantan Tengah", "fdescr":  "Katingan", "ftzone": 7, "flstfl": 0}, 
{"_id": 852, "fnewid":  "BycFYgk1AXABc1M%2FCjYCNFMnVmIBblQ%2FUjAMIQdkXmFTMVJpADgDMQtsVWMAblc4", "fstate":  "Kalimantan Tengah", "fdescr":  "Palangkaraya Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 845, "fnewid":  "ASFTNFxgVCUBc1c7DTAKOwZyBDBWOQBrAWMEKQdkWmVXNQA7CzNUZgViAzUJZ1U6", "fstate":  "Kalimantan Tengah", "fdescr":  "Kotawaringin Barat", "ftzone": 7, "flstfl": 0}, 
{"_id": 846, "fnewid":  "BCRVMg8zB3YAcgdrCzYHNQ15VmJXOFU%2BA2EALQRnCTYCYFdsDTVUZlA3ADYOYFI9", "fstate":  "Kalimantan Tengah", "fdescr":  "Kotawaringin Timur", "ftzone": 7, "flstfl": 0}, 
{"_id": 847, "fnewid":  "ASFTNAA8VyYCcAJuCjdUZw15ADQFagRvDG4DLlU2XGMGZFFqWWEDMQViAzUNY1c4", "fstate":  "Kalimantan Tengah", "fdescr":  "Lamandau", "ftzone": 7, "flstfl": 0}, 
{"_id": 848, "fnewid":  "CipVMl5iBndQIlE9DjMAPARwBjJQP1Q%2FAmAFKFQ3CjUGZFBrCjIAMlcwWW8Ablc4", "fstate":  "Kalimantan Tengah", "fdescr":  "Murungraya", "ftzone": 7, "flstfl": 0}, 
{"_id": 849, "fnewid":  "VXVXMF1hVyZaKARoWWQDPgRwVGAAbwJpVTcGK1s4CjVbOVdsXWUGNFI1WW8Bb1E%2B", "fstate":  "Kalimantan Tengah", "fdescr":  "Pulangpisau", "ftzone": 7, "flstfl": 0}, 
{"_id": 850, "fnewid":  "UXEDZA8zUCFVJwBsWWULPwN3UGQMYwNoUTMGK1s4CTYGZFBrCzNSYFI1WG4LZVY5", "fstate":  "Kalimantan Tengah", "fdescr":  "Seruyan", "ftzone": 7, "flstfl": 0}, 
{"_id": 851, "fnewid":  "BSUEY1pmA3JTIQpmCjZQZQZyU2cGaVc8BWcALQdkXWJRM1JpDjYGNFE2AzUBbwdo", "fstate":  "Kalimantan Tengah", "fdescr":  "Sukamara", "ftzone": 7, "flstfl": 0}, 
{"_id": 866, "fnewid":  "ACBRNl1hAXBWJAVpXWICMFAkCz9WOVU%2BVzUCL1o5DzAAYgI5DzdSYFI1VmAMYlw3", "fstate":  "Kalimantan Timur", "fdescr":  "Berau", "ftzone": 8, "flstfl": 0}, 
{"_id": 867, "fnewid":  "ACBSNVtnB3ZWJAFtWWZRYlElCj5WOVU%2BVTcALVU2DzAAYlFqWWFWZABnWG4NY102", "fstate":  "Kalimantan Timur", "fdescr":  "Bulungan", "ftzone": 8, "flstfl": 0}, 
{"_id": 875, "fnewid":  "BSUHYAwwXSxaKABsDzFTYgN3BTFWOQRvUjBXegZlCzRXNVVuCDAOPFI1ADZeMAds", "fstate":  "Kalimantan Timur", "fdescr":  "Balikpapan Kota", "ftzone": 8, "flstfl": 0}, 
{"_id": 876, "fnewid":  "VXVVMgk1UCFQIgVpXGJUZlMnV2MFalQ%2FVTcBLANgWWYHZQQ%2FCjIDMQFmUGYAblc8", "fstate":  "Kalimantan Timur", "fdescr":  "Bontang Kota", "ftzone": 8, "flstfl": 0}, 
{"_id": 874, "fnewid":  "AyNQN1tnAXABc1A8XGICMgRwCj4MY1I5BWcMIVY1DTIGZAw3WWFSYFI1BDJcMgBr", "fstate":  "Kalimantan Timur", "fdescr":  "Samarinda Kota", "ftzone": 8, "flstfl": 0}, 
{"_id": 877, "fnewid":  "CioAZw8zXC0HdQRoAD5UZwJ2Cz8MYwBrBGYALVAzCTZXNQA7W2NRYwRjADZdM1w3", "fstate":  "Kalimantan Timur", "fdescr":  "Tarakan Kota", "ftzone": 8, "flstfl": 0}, 
{"_id": 868, "fnewid":  "UHADZF1hXSxRIwFtWmVUaAN3VmJRPlQ%2FBWcMIVo5AT5UNldsXGQOPAZhU2UMYgZt", "fstate":  "Kalimantan Timur", "fdescr":  "Kutai Barat", "ftzone": 8, "flstfl": 0}, 
{"_id": 869, "fnewid":  "V3dTNA4yA3IHdVY6XWIFOFElAzdRPlU%2BDW8BLABjXGMFZwM4CzMDMQtsUmQNY1M4", "fstate":  "Kalimantan Timur", "fdescr":  "Kutai Kartanegara", "ftzone": 8, "flstfl": 0}, 
{"_id": 870, "fnewid":  "ASFVMl5iA3JWJABsCTcANFcjV2MGaQNoUDIDLgRnXWIFZwc8DDRUZgptVGIAblY9", "fstate":  "Kalimantan Timur", "fdescr":  "Kutai Timur", "ftzone": 8, "flstfl": 0}, 
{"_id": 873, "fnewid":  "UHAFYlllUCFSIAVpCjQKPQN3VmIBbgZtVTcEKQFiCzRTMQM4WmJUZgptVWMPYVc8", "fstate":  "Kalimantan Timur", "fdescr":  "Mahakam Ulu", "ftzone": 8, "flstfl": 0}, 
{"_id": 872, "fnewid":  "ASEHYF1hUCFTIQRoCDZRZwB0VGAHaABrDW9RfFs4DTJUNlZtDDQBM1UyVWMMYgRv", "fstate":  "Kalimantan Timur", "fdescr":  "Paser", "ftzone": 8, "flstfl": 0}, 
{"_id": 871, "fnewid":  "AiJRNgk1UiNaKAVpXWMEMVYiAzdSPVI5UDJQfQZlAD9TMVVuDzdSYAViU2VaNFw3", "fstate":  "Kalimantan Timur", "fdescr":  "Penajam Paser Utara", "ftzone": 8, "flstfl": 0}, 
{"_id": 878, "fnewid":  "ASFQNwA8USBVJwFtCjQDP1cjVGADbAdsVzVVeFQ3DDNRMwY9CzMBMwViUGYKZFU%2B", "fstate":  "Kalimantan Utara", "fdescr":  "Malinau", "ftzone": 8, "flstfl": 0}, 
{"_id": 879, "fnewid":  "VnYDZFxgVicBcwtnXmACPwRwV2MBbgBrDW9SfwdkWWZbOVFqXGQGNAtsUmReMARv", "fstate":  "Kalimantan Utara", "fdescr":  "Nunukan", "ftzone": 8, "flstfl": 0}, 
{"_id": 880, "fnewid":  "AyMDZFpmUyJUJgpmDj9WYlMnU2cAbwJpB2UHKgdkCTZXNVBrDTVWZAdgBTNeMFA7", "fstate":  "Kalimantan Utara", "fdescr":  "Tana Tidung", "ftzone": 8, "flstfl": 0}, 
{"_id": 659, "fnewid":  "BSVUMws3XSxWJFY0DTEFOFQgBzMHaAVuAWNRfFU2AT4HZQ02DzcCMFA3VGJdM1w3", "fstate":  "Kepulauan Riau", "fdescr":  "Bintan", "ftzone": 7, "flstfl": 0}, 
{"_id": 658, "fnewid":  "UnJWMQ8zXC1RIwNhDjJQbAVxU2cNYlM4VjRWewFiDDNWNFFqDjYGNFI1VmAPYVY9", "fstate":  "Kepulauan Riau", "fdescr":  "Karimun", "ftzone": 7, "flstfl": 0}, 
{"_id": 662, "fnewid":  "UnJQNwE9UyIHdQVnXmEHMQF1VmJRPgFqB2UDLlY1DzBbOQ02DDQDMQNkBzEAblY9", "fstate":  "Kepulauan Riau", "fdescr":  "Kepulauan Anambas", "ftzone": 7, "flstfl": 0}, 
{"_id": 664, "fnewid":  "BiZUM1llUCFRI1MxDTJXZwF1UGQHaAJpUTMFKFo5AD8AYgU%2BWmIBMwZhADZbNQZt", "fstate":  "Kepulauan Riau", "fdescr":  "Batam Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 663, "fnewid":  "ACBQN11hUyJRIwFjCDcAN1QgBzNQPwRvA2FWe1IxCTYAYgM4WWEENlI1VGIKZANo", "fstate":  "Kepulauan Riau", "fdescr":  "Tanjungpinang Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 660, "fnewid":  "UnIFYgo2AXBaKApoW2RUYFQgBzMBblU%2BVTcFKFIxCjUHZQw3WmJUZgJlUGYKZFY9", "fstate":  "Kepulauan Riau", "fdescr":  "Lingga", "ftzone": 7, "flstfl": 0}, 
{"_id": 661, "fnewid":  "BCQFYl5iBndXJQZkDTILPlElBjIHaAVuBWcEKQFiWWZXNVJpDDRUZgViBzEMYgds", "fstate":  "Kepulauan Riau", "fdescr":  "Natuna", "ftzone": 7, "flstfl": 0}, 
{"_id": 1025, "fnewid":  "BCRYPw8zB3YCcABlDDUGMFc1C35XNQZuVTpSM1EtDTAAYw0wXGNVYQBhWWtcNgBsB2E%3D", "fstate":  "Kepulauan Riau", "fdescr":  "Pekajang Kab. Lingga", "ftzone": 7, "flstfl": 0}, 
{"_id": 1028, "fnewid":  "CipVMgE9VSQFdwFkDzYFM1E%2BUSRRMwJqA2xRMAZ6CzZVNgM%2BXmFWYgprVGYLYQdrB2E%3D", "fstate":  "Kepulauan Riau", "fdescr":  "Pulau Laut Kab. Natuna", "ftzone": 7, "flstfl": 0}, 
{"_id": 1027, "fnewid":  "ASFZPlllVCUGdFYzXGUKPFAwBXBVNwdvBGsEZQZ6ATxQM1BtXmFSZlc2BDYMZlQ4BmA%3D", "fstate":  "Kepulauan Riau", "fdescr":  "Pulau Midai Kab. Natuna", "ftzone": 7, "flstfl": 0}, 
{"_id": 1026, "fnewid":  "AiJWMVpmBHVUJlA1XWQBNwBhViNQMgZuBGtWN1MvAD1XNAM%2BWmVVYVc2BzUBa1A8BmA%3D", "fstate":  "Kepulauan Riau", "fdescr":  "Pulau Serasan Kab. Natuna", "ftzone": 7, "flstfl": 0}, 
{"_id": 1024, "fnewid":  "V3dUMwo2USBXJQFkATgEMgJhBHECYAFpBGsAYQB8XGECYQ0wXmEDNwZnV2ULYVQ4UjQ%3D", "fstate":  "Kepulauan Riau", "fdescr":  "Pulau Tambelan Kab. Bintan", "ftzone": 7, "flstfl": 0}, 
{"_id": 649, "fnewid":  "CipTNF5iAXBaKAZkCTQCPwRwBTEMY1c8UTMHKlU2DDMFZwQ%2FW2NWZAViADYIZl02", "fstate":  "Lampung", "fdescr":  "Bandarlampung Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 650, "fnewid":  "CysAZw8zVicHdVQ2WmZRZQF1BzMHaFA7A2EGKwZlDDMGZFFqXGQAMlE2UmReMFA7", "fstate":  "Lampung", "fdescr":  "Metro Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 636, "fnewid":  "AyMEY1xgB3ZRIwZkDzUAMlElCj5WOQZtAGIHKlY1XGMCYFFqWmIGNFYxUGYPYQFq", "fstate":  "Lampung", "fdescr":  "Lampung Barat", "ftzone": 7, "flstfl": 0}, 
{"_id": 637, "fnewid":  "ASFXMFtnXC1aKFQ2XmQKOVAkADRSPQFqVTcCLwdkWWZSMAU%2BCzMCMFA3VWNdM1Q%2F", "fstate":  "Lampung", "fdescr":  "Lampung Selatan", "ftzone": 7, "flstfl": 0}, 
{"_id": 638, "fnewid":  "V3cCZVllVCVaKANhADoFOQJ2UWUBblQ%2FA2FSfwBjCjVVNwI5DzcGNAZhU2UJZ1M4", "fstate":  "Lampung", "fdescr":  "Lampung Tengah", "ftzone": 7, "flstfl": 0}, 
{"_id": 639, "fnewid":  "V3dVMgA8USBaKApoDTcHOgVxBzMDbAJpDG4EKQZlXWJTMQE6ADhTYQdgVmBaNFU%2B", "fstate":  "Lampung", "fdescr":  "Lampung Timur", "ftzone": 7, "flstfl": 0}, 
{"_id": 640, "fnewid":  "BycDZA0xVidXJQRmWWRWYgN3BTEBbg5lAmBWe1c0DzBQMlBrATlUZgtsBTMKZFQ%2F", "fstate":  "Lampung", "fdescr":  "Lampung Utara", "ftzone": 7, "flstfl": 0}, 
{"_id": 647, "fnewid":  "AiJVMg4yVyZQIgtpXGEDMA15Cj4BblQ%2FUTMFKFAzW2RUNgY9DjYHNVcwUGYJZ1E6", "fstate":  "Lampung", "fdescr":  "Mesuji", "ftzone": 7, "flstfl": 0}, 
{"_id": 645, "fnewid":  "AyMFYlpmA3JVJwBiWmcLOg15Cz8GaQRvDG5XelU2DjFTMQY9W2MCMFcwWW9eMAds", "fstate":  "Lampung", "fdescr":  "Pesawaran", "ftzone": 7, "flstfl": 0}, 
{"_id": 648, "fnewid":  "AyMFYg0xUSAFdwNhXGEBPVMnATVSPQNoAGJVeFY1CjVRMwM4ADgENgJlUmRaNFw3", "fstate":  "Lampung", "fdescr":  "Pesisir Barat", "ftzone": 7, "flstfl": 0}, 
{"_id": 646, "fnewid":  "VnYFYgo2AXBRI1Y0XGECMFYiVmJRPlA7BGZVeFQ3XmFXNVBrXWVTYQptUmReMFE6", "fstate":  "Lampung", "fdescr":  "Pringsewu", "ftzone": 7, "flstfl": 0}, 
{"_id": 641, "fnewid":  "UnJTNAo2VicGdAJgCTQHMgJ2Cj5QP1A7DG4BLFU2DDNSMFVuWmJRYwRjUWdZN1A7", "fstate":  "Lampung", "fdescr":  "Tanggamus", "ftzone": 7, "flstfl": 0}, 
{"_id": 642, "fnewid":  "ASFUMwk1VCVVJ1Q2CTQCNAx4AzcDbAZtVTdRfFc0W2QAYlVuWWEDMQFmV2EMYlI5", "fstate":  "Lampung", "fdescr":  "Tulangbawang", "ftzone": 7, "flstfl": 0}, 
{"_id": 643, "fnewid":  "CytYP15iUCFaKANhWmdTZAJ2UWVVOgRvDW8FKARnCzRTMQA7W2MPPQdgBzEAbgds", "fstate":  "Lampung", "fdescr":  "Tulangbawang Barat", "ftzone": 7, "flstfl": 0}, 
{"_id": 644, "fnewid":  "BiYAZ11hAXABc1Q2ATxWZlElUWVSPQ9kVzVWewNgWmVaOAE6XGQDMQViU2UOYFw3", "fstate":  "Lampung", "fdescr":  "Waykanan", "ftzone": 7, "flstfl": 0}, 
{"_id": 959, "fnewid":  "CytUMwE9B3ZaKAtmDTEAPVAkVmIFagNoAmBXegBjXmFSMFVuDjYGNFUyUWcAblM2", "fstate":  "Maluku", "fdescr":  "Buru", "ftzone": 9, "flstfl": 0}, 
{"_id": 960, "fnewid":  "AyNYP11hXC1RIwVoDTJRZQJ2AzdWOVA7UDJXegNgW2QAYgM4DzcENlcwWW8MYlw5", "fstate":  "Maluku", "fdescr":  "Buru Selatan", "ftzone": 9, "flstfl": 0}, 
{"_id": 961, "fnewid":  "UHAFYgg0BndVJwpnXWJXYg15V2MDbA5lDW8DLlQ3WmVWNAA7CDBVZwtsAjQNY1Qx", "fstate":  "Maluku", "fdescr":  "Kepulauan Aru", "ftzone": 9, "flstfl": 0}, 
{"_id": 968, "fnewid":  "UXEEY11hVidSIFE8CjVTbwx4BjIBbgdsUTNVeAdkDDNSMAA7CjJWZAFmVGIKZARh", "fstate":  "Maluku", "fdescr":  "Ambon Kota", "ftzone": 9, "flstfl": 0}, 
{"_id": 969, "fnewid":  "UXEHYAwwVSRVJ1M%2BAD9XagVxCj5WOVU%2BBGYMIVEyAD8AYlVuWWFUZlI1UmRbNVw5", "fstate":  "Maluku", "fdescr":  "Tual Kota", "ftzone": 9, "flstfl": 0}, 
{"_id": 964, "fnewid":  "UnJYPwE9BHVTIQFsXWJQYARwAzdRPlc8DW8DLlAzAD9UNlBrDzcDMVUyVmBcMgZj", "fstate":  "Maluku", "fdescr":  "Maluku Barat Daya", "ftzone": 9, "flstfl": 0}, 
{"_id": 965, "fnewid":  "AiJYP1pmXSwCcFM%2BXmELOgZyBTEDbFU%2BDW9VeAZlDjEFZwc8ADgFNwBnADZcMlM2", "fstate":  "Maluku", "fdescr":  "Maluku Tengah", "ftzone": 9, "flstfl": 0}, 
{"_id": 966, "fnewid":  "AyNQNwk1VyZXJQtmXmEGNARwBTENYgFqUTNRfANgWmVTMQ02DjZTYQZhVGIIZgRh", "fstate":  "Maluku", "fdescr":  "Maluku Tenggara", "ftzone": 9, "flstfl": 0}, 
{"_id": 967, "fnewid":  "VXVVMg0xBndTIVc6AT4AM1QgUWVRPlA7DW9VeAdkDTJaOFBrXGRVZwViVWMMYlYz", "fstate":  "Maluku", "fdescr":  "Maluku Tenggara Barat", "ftzone": 9, "flstfl": 0}, 
{"_id": 962, "fnewid":  "CipQNwk1UyIHdQZrCDcEMgB0Cz9QPwRvAWMMIVU2WWYBYwQ%2FCjJUZgViV2EBbwZj", "fstate":  "Maluku", "fdescr":  "Seram Bagian Barat", "ftzone": 9, "flstfl": 0}, 
{"_id": 963, "fnewid":  "BSVSNQ4yBHUCcAVoW2QKPQdzCz8HaFc8BWdSfwNgDTJSMFVuCjIHNQJlV2EAblA1", "fstate":  "Maluku", "fdescr":  "Seram Bagian Timur", "ftzone": 9, "flstfl": 0}, 
{"_id": 970, "fnewid":  "CioHYAg0AHEAcgFsCjQFMQF1ADQDbFM4AGIMIQBjWWYGZFJpW2NUZgViADYLZVE0", "fstate":  "Maluku Utara", "fdescr":  "Halmahera Barat", "ftzone": 9, "flstfl": 0}, 
{"_id": 971, "fnewid":  "UnJQN1xgXC0Fd1c6AD4FMAF1UGQBbg5lAmAHKlU2DjEFZwM4W2NRYwptUGYOYFE0", "fstate":  "Maluku Utara", "fdescr":  "Halmahera Selatan", "ftzone": 9, "flstfl": 0}, 
{"_id": 972, "fnewid":  "BSVZPg8zXC1XJQNuWWcCNFYiCj5QP1Q%2FUDIBLFIxDzAHZQQ%2FW2NVZ1cwAjQIZlE0", "fstate":  "Maluku Utara", "fdescr":  "Halmahera Tengah", "ftzone": 9, "flstfl": 0}, 
{"_id": 973, "fnewid":  "VnYCZVtnXC1SIABtDTNUY1ElU2cFagFqAWMCLwRnCTYHZQc8CzNRY1cwUmReMANm", "fstate":  "Maluku Utara", "fdescr":  "Halmahera Timur", "ftzone": 9, "flstfl": 0}, 
{"_id": 974, "fnewid":  "V3cHYAE9BncCcFE8W2UFNVcjATUEawJpDW8BLABjCjUGZAw3XWUCMAptWW8MYlw5", "fstate":  "Maluku Utara", "fdescr":  "Halmahera Utara", "ftzone": 9, "flstfl": 0}, 
{"_id": 975, "fnewid":  "ACAEYwo2XSxUJgdqXWNRYAF1BjIGaQBrDG5XegFiDDNXNQA7WWEHNQFmUWdaNAdi", "fstate":  "Maluku Utara", "fdescr":  "Kepulauan Sula", "ftzone": 9, "flstfl": 0}, 
{"_id": 978, "fnewid":  "V3cCZV5iVCVaKAVoCjQLNwN3AzdWOQFqBWdXelo5XWJQMlFqCjJTYQJlVWMJZ1Yz", "fstate":  "Maluku Utara", "fdescr":  "Ternate Kota", "ftzone": 9, "flstfl": 0}, 
{"_id": 979, "fnewid":  "UnJWMQg0BHVTIVA9DzECPwRwCj4BblQ%2FBGYDLlY1AD9VNwA7DTUFN1I1AjRbNVQx", "fstate":  "Maluku Utara", "fdescr":  "Tidore Kota", "ftzone": 9, "flstfl": 0}, 
{"_id": 976, "fnewid":  "ACBTNAs3VCVVJwZrCzVXZQx4V2MBblM4VjQALVIxWmUAYgU%2BATkHNQNkBDIIZgFk", "fstate":  "Maluku Utara", "fdescr":  "Pulau Morotai", "ftzone": 9, "flstfl": 0}, 
{"_id": 977, "fnewid":  "BiZTNFtnVidXJQBtAT8AM1YiBDAHaFI5BGYNIFAzXGNWNFJpATkHNQptUGYPYQdi", "fstate":  "Maluku Utara", "fdescr":  "Pulau Taliabu", "ftzone": 9, "flstfl": 0}, 
{"_id": 793, "fnewid":  "UHBRNgk1UiNQIgVmXW0FMgN3UWUEa1Q%2FUDIFKFo5DTICYFVuADhRYwJlUGYMYgFk", "fstate":  "NTB", "fdescr":  "Bima", "ftzone": 8, "flstfl": 0}, 
{"_id": 794, "fnewid":  "AiIFYgg0USBQIlc0Xm5QYA15BzNSPVA7BWcHKlEyCDdSMFJpCDACMABnUGZaNARh", "fstate":  "NTB", "fdescr":  "Dompu", "ftzone": 8, "flstfl": 0}, 
{"_id": 802, "fnewid":  "BiZUMw0xA3JQIlE9XmdUYlElUGQGaQBrAGINIABjWWZRM1BrWmIAMgptUGYKZFM2", "fstate":  "NTB", "fdescr":  "Bima Kota", "ftzone": 8, "flstfl": 0}, 
{"_id": 801, "fnewid":  "UHBRNgo2VyZTIVA8WmMHMlQgUGQBblI5BmQFKFMwDzAGZFdsDTVSYARjVmALZQdi", "fstate":  "NTB", "fdescr":  "Mataram Kota", "ftzone": 8, "flstfl": 0}, 
{"_id": 795, "fnewid":  "AyMAZw8zBndaKFY1XW0DMlElBzMDbAJpUDIDLgNgWmVWNFBrXGQOPAJlVmAIZgRh", "fstate":  "NTB", "fdescr":  "Lombok Barat", "ftzone": 8, "flstfl": 0}, 
{"_id": 796, "fnewid":  "ACBWMVxgA3IGdFMwXW0FN1QgVmIMYwRvUjAMIVMwXmEHZQY9ATkFNwptADZeMF04", "fstate":  "NTB", "fdescr":  "Lombok Tengah", "ftzone": 8, "flstfl": 0}, 
{"_id": 797, "fnewid":  "CysAZwwwB3ZTIQVmADAGNVAkBzMNYgJpAGINIAFiAT4CYAY9XmZRY1YxBzFeMAZj", "fstate":  "NTB", "fdescr":  "Lombok Timur", "ftzone": 8, "flstfl": 0}, 
{"_id": 798, "fnewid":  "UHBRNg4yUyJSIFQ3XGwLN1YiAjZXOFI5DG4CL1Y1XWJWNFdsDDQPPVUyUmQOYFA1", "fstate":  "NTB", "fdescr":  "Lombok Utara", "ftzone": 8, "flstfl": 0}, 
{"_id": 799, "fnewid":  "UnICZVxgUSBSIFAzCztWawVxADRRPg9kB2VWewNgAD8GZAE6XWUGNFI1BzFdM1E0", "fstate":  "NTB", "fdescr":  "Sumbawa", "ftzone": 8, "flstfl": 0}, 
{"_id": 800, "fnewid":  "VXUHYAo2BHUGdAVpXGUCNgZyVGACbQFqUDIDLlY1CTZXNQA7XWUCMAViUWdaNFUw", "fstate":  "NTB", "fdescr":  "Sumbawa Barat", "ftzone": 8, "flstfl": 0}, 
{"_id": 803, "fnewid":  "VnYDZAo2AHFWJAZqXWRXYFQgCj5RPlQ%2FVzVWewBjCDdaOAA7DjYENgViUGZZNwBl", "fstate":  "NTT", "fdescr":  "Alor", "ftzone": 8, "flstfl": 0}, 
{"_id": 804, "fnewid":  "CipYPw8zXSxQIlQ4XWRQYAN3BzNSPVM4AGIFKFEyW2QGZAA7XWUOPFE2UmReMFYz", "fstate":  "NTT", "fdescr":  "Belu", "ftzone": 8, "flstfl": 0}, 
{"_id": 805, "fnewid":  "BSVXMAk1AHFWJFQ4XGVRYFYiBzNVOlI5VzVVeFY1DjEBY1JpDDRTYQdgUWdcMgBl", "fstate":  "NTT", "fdescr":  "Ende", "ftzone": 8, "flstfl": 0}, 
{"_id": 806, "fnewid":  "BSVXMF5iVSRTIQdrW2IAMlYiVGAGaVA7DW8GK1c0DzAGZFBrATlTYQViWG5cMlw5", "fstate":  "NTT", "fdescr":  "Flores Timur", "ftzone": 8, "flstfl": 0}, 
{"_id": 824, "fnewid":  "V3dZPl5iXSwGdFA8WmELO1ElBTEGaVc8BGYMIQFiWWYGZFZtDDRWZFUyBzEPYVw5", "fstate":  "NTT", "fdescr":  "Kupang Kota", "ftzone": 8, "flstfl": 0}, 
{"_id": 807, "fnewid":  "CipXMAk1AHECcFY6CzIHNAx4BzMCbQBrUDJSfwZlDzAAYgw3ATlWZFE2WW8LZVw5", "fstate":  "NTT", "fdescr":  "Kupang", "ftzone": 8, "flstfl": 0}, 
{"_id": 808, "fnewid":  "AiIAZw4yVSRXJQZqXWQCPlcjCz9QPwdsA2ENIFY1AD9aOA02CjIDMQptWG4OYABl", "fstate":  "NTT", "fdescr":  "Lembata", "ftzone": 8, "flstfl": 0}, 
{"_id": 823, "fnewid":  "CipVMgo2B3ZVJwZqWWILPFElAzcFag5lDW8EKQZlDDMCYA02CTEGNARjVWMJZ1M2", "fstate":  "NTT", "fdescr":  "Malaka", "ftzone": 8, "flstfl": 0}, 
{"_id": 809, "fnewid":  "UnJTNAA8VCVXJQZqWWAFOA15Cj5VOg5lVzVQfQBjAD9TMQ02DzcBM1YxWG4AbgNm", "fstate":  "NTT", "fdescr":  "Manggarai", "ftzone": 8, "flstfl": 0}, 
{"_id": 810, "fnewid":  "BCQAZws3UCEFdwRoCDAANFYiBjJWOVU%2BBWdWe1IxCjUFZwU%2BXGQPPVcwBTMAblw5", "fstate":  "NTT", "fdescr":  "Manggarai Barat", "ftzone": 8, "flstfl": 0}, 
{"_id": 811, "fnewid":  "CipRNg0xVCVaKABsXWULPg15V2MEa1Q%2FAGIFKFEyAT4FZww3CDAAMlI1AjQOYFYz", "fstate":  "NTT", "fdescr":  "Manggarai Timur", "ftzone": 8, "flstfl": 0}, 
{"_id": 812, "fnewid":  "BycFYg8zBndVJ1A8WWECNARwATUHaABrAmABLFU2AD9aOAE6ATlUZgtsU2VbNQRh", "fstate":  "NTT", "fdescr":  "Nagekeo", "ftzone": 8, "flstfl": 0}, 
{"_id": 813, "fnewid":  "AyMFYlllUSBWJFM%2FADgCNQx4BzMFagdsDW8HKgNgDTIGZFdsDTVTYQViV2FeMFE0", "fstate":  "NTT", "fdescr":  "Ngada", "ftzone": 8, "flstfl": 0}, 
{"_id": 814, "fnewid":  "AyNQNwk1UiNaKAZqCDALOwZyUGRRPlA7A2EDLlY1DzBXNQw3ADgGNANkBzEJZ1Qx", "fstate":  "NTT", "fdescr":  "Rote Ndao", "ftzone": 8, "flstfl": 0}, 
{"_id": 820, "fnewid":  "ACAHYAA8AXBbKVY6CDMHMwx4AjZSPQBrBGYGK1Y1DjEGZAI5XmYFNwZhU2VaNAdi", "fstate":  "NTT", "fdescr":  "Saburaijua", "ftzone": 8, "flstfl": 0}, 
{"_id": 815, "fnewid":  "VXUAZw4yVSRWJAVpW2NRYARwU2cFagVuAWNWewFiW2RbOQ02DDQFNwtsBzEBb1Qx", "fstate":  "NTT", "fdescr":  "Sikka", "ftzone": 8, "flstfl": 0}, 
{"_id": 816, "fnewid":  "AyNXMFtnVyZVJ1M%2FCjIKOA15U2cNYgZtUjAGK1o5DDNSMFFqXmYOPFYxVmBdM1Qx", "fstate":  "NTT", "fdescr":  "Sumba Barat", "ftzone": 8, "flstfl": 0}, 
{"_id": 817, "fnewid":  "UnJUM15iB3ZSIABsADgHNAB0BTEBbgJpUjAEKVAzCDcGZAQ%2FWmIBMwViAjRdM1I3", "fstate":  "NTT", "fdescr":  "Sumba Barat Daya", "ftzone": 8, "flstfl": 0}, 
{"_id": 818, "fnewid":  "V3dZPl1hVyZSIFY6CzMHO1cjADRXOARvVTdVeABjCjVTMQc8CjJTYVE2WG4MYlw5", "fstate":  "NTT", "fdescr":  "Sumba Tengah", "ftzone": 8, "flstfl": 0}, 
{"_id": 819, "fnewid":  "UnIFYgs3UiNUJlc7WmIFOFcjU2cMYw9kBWdQfQNgWWYHZQ02ATlUZlUyBDJZNwdi", "fstate":  "NTT", "fdescr":  "Sumba Timur", "ftzone": 8, "flstfl": 0}, 
{"_id": 821, "fnewid":  "CysHYF5iVSRQIlE9W2AHMgN3AzcFalA7VzVRfFIxCTZWNAY9ADhVZ1UyUmQIZlUw", "fstate":  "NTT", "fdescr":  "Timor Tengah Selatan", "ftzone": 8, "flstfl": 0}, 
{"_id": 822, "fnewid":  "CioAZw8zA3JaKAZqXmULPQB0V2MAb1Q%2FUTMFKAFiDDMAYgM4XmYHNVcwBTMIZlw5", "fstate":  "NTT", "fdescr":  "Timor Tengah Utara", "ftzone": 8, "flstfl": 0}, 
{"_id": 980, "fnewid":  "UHBXMFxgUSBWJAdqXG0KPlAkUGQDbFU%2BB2UALVs4CzRbOQA7CjIDMVA3WW9eMAdi", "fstate":  "Papua", "fdescr":  "Asmat", "ftzone": 9, "flstfl": 0}, 
{"_id": 981, "fnewid":  "CioAZ15iXC1XJQRpCThRZFElATUNYgBrBmQBLFc0AT5VNwc8CzNWZFE2UGZeMFQx", "fstate":  "Papua", "fdescr":  "Biaknumfor", "ftzone": 9, "flstfl": 0}, 
{"_id": 982, "fnewid":  "BydSNQg0VCUFd1Q5WWgANgVxVGAHaAdsUTNVeFo5DTJTMVJpATlUZgdgVmANYwRh", "fstate":  "Papua", "fdescr":  "Bovendigoel", "ftzone": 9, "flstfl": 0}, 
{"_id": 1004, "fnewid":  "AiJVMgo2B3ZaKAdiXmdWYgxvVyIDYVc%2FVTpWNwZ6CzZUNwA9CjVRZQJjVWcKYAdrVT0%3D", "fstate":  "Papua", "fdescr":  "Deiyai", "ftzone": 9, "flstfl": 0}, 
{"_id": 1005, "fnewid":  "VXVWMQo2A3JWJApvXmcHM1EzVyJSMFA4Uj0AYVEtCTQBYgU4DDNRZQJjUmAAalA8Uzs%3D", "fstate":  "Papua", "fdescr":  "Dogiyai", "ftzone": 9, "flstfl": 0}, 
{"_id": 1006, "fnewid":  "UHAEYwE9B3ZSIFYzCzJUYANiAHVQMgRsBWpWN1EtXGEGZVJvDTJRZVIzAzFcNgFtUjo%3D", "fstate":  "Papua", "fdescr":  "Intan Jaya", "ftzone": 9, "flstfl": 0}, 
{"_id": 983, "fnewid":  "BCRRNl5iXSwGdANuDj8BNlMnBjIFag5lAmAMIVMwDjFTMQw3CjIHNQNkV2EJZ1A1", "fstate":  "Papua", "fdescr":  "Jayapura", "ftzone": 9, "flstfl": 0}, 
{"_id": 1007, "fnewid":  "BCQDZA4yVSQFdwZjADlWYlY2B3JXNQNrVTpWN1YqAD0HZFVoCTYDNwBhVGYMZlY6BW0%3D", "fstate":  "Papua", "fdescr":  "Jayawijaya", "ftzone": 9, "flstfl": 0}, 
{"_id": 984, "fnewid":  "VXVXMFllXSxXJQdqXm9QYAZyUGQHaFU%2BUjBRfFo5DjFaOFFqCTFTYVUyWG4JZwRh", "fstate":  "Papua", "fdescr":  "Keerom", "ftzone": 9, "flstfl": 0}, 
{"_id": 1009, "fnewid":  "V3dVMl1hXC1XJVQxDTQGMlc5USQDYQVtUD9SM1snDTBTMAM%2BDDNUYARlAzEMZl0xUzs%3D", "fstate":  "Papua", "fdescr":  "Kepulauan Yapen", "ftzone": 9, "flstfl": 0}, 
{"_id": 1008, "fnewid":  "CytZPg0xXC1aKAdiXGVQZAZpC34Nb1Q8Uj0BYAZ6AD1XNFBtDTIFMQtqBDYOZAdrUDg%3D", "fstate":  "Papua", "fdescr":  "Jayapura Kota", "ftzone": 9, "flstfl": 0}, 
{"_id": 1002, "fnewid":  "AiIAZwk1BHUHdQtuCzJXYwBlUyYBY1Q8UD9SM1snCDUAY1JvDTIPOwRlAzENZ1E9AGg%3D", "fstate":  "Papua", "fdescr":  "Lanny Jaya", "ftzone": 9, "flstfl": 0}, 
{"_id": 993, "fnewid":  "BCRRNltnVidUJgBtWWkFMgN3AzdWOQBrVzUCLwFiXGNUNlJpDDRTYQFmWW9dMwRh", "fstate":  "Papua", "fdescr":  "Mamberamo Raya", "ftzone": 9, "flstfl": 0}, 
{"_id": 994, "fnewid":  "BycEYw8zVyYHdQtmATEENAB0UWVWOQRvUTMFKAZlCzRSMA02XWUFN1cwBDIIZgdi", "fstate":  "Papua", "fdescr":  "Mamberamo Tengah", "ftzone": 9, "flstfl": 0}, 
{"_id": 985, "fnewid":  "BiYCZV1hUCFSIFE8CzoLOgRwAjYGaQRvUDIHKlU2XmFQMgQ%2FWWFWZFA3VWMLZVYz", "fstate":  "Papua", "fdescr":  "Mappi", "ftzone": 9, "flstfl": 0}, 
{"_id": 986, "fnewid":  "AyMHYFpmBHVUJgtmWmtQYgx4BTEFagNoBWcDLgdkCzQCYAA7DDQFN1UyADZdMwBl", "fstate":  "Papua", "fdescr":  "Merauke", "ftzone": 9, "flstfl": 0}, 
{"_id": 987, "fnewid":  "VXVTNAA8XSwGdAZrXWxUZwN3ATUDbABrA2FXegRnW2RVNwc8DjZTYQJlUGYKZFM2", "fstate":  "Papua", "fdescr":  "Mimika", "ftzone": 9, "flstfl": 0}, 
{"_id": 1000, "fnewid":  "CioAZ1xgXC0HdQNmCDELP1E2BnNVNw9nAm1SM1UpXGEFZlFsXGMOOlc2UWNbMVQ4B28%3D", "fstate":  "Papua", "fdescr":  "Nabire", "ftzone": 9, "flstfl": 0}, 
{"_id": 1003, "fnewid":  "BCRRNltnVidUJlQxATgFMQBkAXRSMFA4B2gEZQZ6CzZVNgY7AD8DNwVkAjAAal0xUjo%3D", "fstate":  "Papua", "fdescr":  "Nduga", "ftzone": 9, "flstfl": 0}, 
{"_id": 988, "fnewid":  "ASFUMwE9BncAcgRpW2oDPwdzCz9WOQJpUTMEKVQ3XWICYAc8CjJTYQptVmBeMFI3", "fstate":  "Papua", "fdescr":  "Paniai", "ftzone": 9, "flstfl": 0}, 
{"_id": 989, "fnewid":  "BSUFYgg0XC1SIAFsXm9XalQgAjZVOgdsVjQALQZlXmFVNwI5CTEFNwJlVmAPYVcy", "fstate":  "Papua", "fdescr":  "Pegunungan Bintang", "ftzone": 9, "flstfl": 0}, 
{"_id": 990, "fnewid":  "ACAEY15iUyIHdQZrDz8BNQRwCj4FalA7UDIEKVQ3AD9bOVFqCTFRYwptWG4AblYz", "fstate":  "Papua", "fdescr":  "Puncak", "ftzone": 9, "flstfl": 0}, 
{"_id": 991, "fnewid":  "CytQNwwwBHVVJwJvDDwLPgx4VmIMYwZtUjAMIQBjCTYAYldsXWUGNAFmWG4OYAFk", "fstate":  "Papua", "fdescr":  "Puncakjaya", "ftzone": 9, "flstfl": 0}, 
{"_id": 992, "fnewid":  "CioEY11hA3IFdwdqCjpRZwF1ADQBbgNoBWcDLls4AT5bOQM4DDQPPVYxBzFcMlM2", "fstate":  "Papua", "fdescr":  "Sarmi", "ftzone": 9, "flstfl": 0}, 
{"_id": 995, "fnewid":  "BydQNwo2AHEBcwFsCztTYgB0ADRXOFc8VjRRfFQ3CzRVNw02XGRVZwNkADZeMABl", "fstate":  "Papua", "fdescr":  "Supiori", "ftzone": 9, "flstfl": 0}, 
{"_id": 996, "fnewid":  "BCRSNQ4yVCUAclM%2BW2sBMwF1AjYFag5lBWdVeFY1DjFTMVZtDTUAMgdgU2VZN1A1", "fstate":  "Papua", "fdescr":  "Tolikara", "ftzone": 9, "flstfl": 0}, 
{"_id": 999, "fnewid":  "ASFUMwA8UiMHdQNuXGwGO1MnVmIHaAJpB2UHKlY1AT5QMgM4XmYENlYxADZeMFE0", "fstate":  "Papua", "fdescr":  "Waropen", "ftzone": 9, "flstfl": 0}, 
{"_id": 997, "fnewid":  "AyNVMgs3UiNQIgVoDz9QYwN3ADQAbwFqUjAMIVEyCjUAYgE6CzMGNFcwVGIKZAdi", "fstate":  "Papua", "fdescr":  "Yahukimo", "ftzone": 9, "flstfl": 0}, 
{"_id": 1001, "fnewid":  "ASFWMQ8zVCVTIQJnDzZWYlE3AXRVNwZuA2xVNAF9AD1WNQY7XWIOOlY3AzEKYFA8VDw%3D", "fstate":  "Papua", "fdescr":  "Yalimo", "ftzone": 9, "flstfl": 0}, 
{"_id": 998, "fnewid":  "AyNSNV1hAXBaKFM%2BADAEOAx4VGAHaANoBWdRfFs4CTZRMwA7W2MGNFE2AjQPYVw5", "fstate":  "Papua", "fdescr":  "Yapen Waropen", "ftzone": 9, "flstfl": 0}, 
{"_id": 1010, "fnewid":  "UnIFYlxgVCVSIAVgDzZWY1QzA3YNbwNrAm1VNAd7WmdRMg0wCDdTZwFgUWMOZVM%2FUDI%3D", "fstate":  "Papua Barat", "fdescr":  "Fak-Fak", "ftzone": 9, "flstfl": 0}, 
{"_id": 1011, "fnewid":  "BydYPw0xUyIAcgZjXWQFMAJkVCFRMwFpA2wEZVAsXGFWNVVoW2QOOgtqBDYIYwdrUDI%3D", "fstate":  "Papua Barat", "fdescr":  "Kaimana", "ftzone": 9, "flstfl": 0}, 
{"_id": 1022, "fnewid":  "BCQEY15iBncCcAtuATgDNQdiAndSMARsUD9XNgB8DjMFZlZrCzQDN1c2UmBaMVY6UjA%3D", "fstate":  "Papua Barat", "fdescr":  "Sorong Kota", "ftzone": 9, "flstfl": 0}, 
{"_id": 1013, "fnewid":  "BSUAZwwwUCFVJwJnDDVXYlYyUyZWNABoUT4MbVYqW2ZSMQwxWmUDNwtqUGJdNgRoVDY%3D", "fstate":  "Papua Barat", "fdescr":  "Manokwari", "ftzone": 9, "flstfl": 0}, 
{"_id": 1014, "fnewid":  "BSUDZAs3XSxXJVE0CjMHMgNgViMFZwNrDGMCYwB8DzIAYwA9CDcANAtqVmQIY1c7B2U%3D", "fstate":  "Papua Barat", "fdescr":  "Manokwari Selatan", "ftzone": 9, "flstfl": 0}, 
{"_id": 1020, "fnewid":  "VnZWMQk1B3YGdABlAThRZ1E2ViNRM1I6VjkAYVUpXWBRMgE8DjEFMQtqVmQBalU5UjA%3D", "fstate":  "Papua Barat", "fdescr":  "Maybrat", "ftzone": 9, "flstfl": 0}, 
{"_id": 1021, "fnewid":  "BycCZQwwVCVSIAVgWmMANgdhUSQAYgFpVzgCYwd7DTBRMgE8DDNWYgFgAjBZMlA8VjQ%3D", "fstate":  "Papua Barat", "fdescr":  "Pegunungan Arfak", "ftzone": 9, "flstfl": 0}, 
{"_id": 1012, "fnewid":  "VnYHYFxgUiNaKABlXWRRZFcyAncHZVc%2FVTpWN1crCzYGZVdqDDMBNVU0BDZZMgRoAmA%3D", "fstate":  "Papua Barat", "fdescr":  "Rajaampat", "ftzone": 9, "flstfl": 0}, 
{"_id": 1015, "fnewid":  "UHAHYAA8VSQGdFA1CDEHMlQ2BnMFZ1A4DWIHZlsnXmNaOVVoAD8EMFAxADJbMFQ4UzE%3D", "fstate":  "Papua Barat", "fdescr":  "Sorong", "ftzone": 9, "flstfl": 0}, 
{"_id": 1016, "fnewid":  "CytZPg8zBncCcFM2DDVUYQdmAXRVNwZuAG9QMVsnDjNaOVdqDjFRZQVkWWsBalc7BmQ%3D", "fstate":  "Papua Barat", "fdescr":  "Sorong Selatan", "ftzone": 9, "flstfl": 0}, 
{"_id": 1019, "fnewid":  "AiJWMQE9UyJQIgdiDTQCNwJsAndXNVI6UT5RMFomWWRWNQwxDjEFMVc2ADIIY10xUDI%3D", "fstate":  "Papua Barat", "fdescr":  "Tambrauw", "ftzone": 9, "flstfl": 0}, 
{"_id": 1017, "fnewid":  "V3cFYl1hUyJQIgFkDTQDNgVlAXQMbgZuDGNWN1snCTRUNwwxWWYFMQVkWWsJYlc7B2U%3D", "fstate":  "Papua Barat", "fdescr":  "Telukbintuni", "ftzone": 9, "flstfl": 0}, 
{"_id": 1018, "fnewid":  "BiZYP1tnAHFQIgpvATgBNABvBnMNbwNrVToGZ1MvCDVVNgE8WmVUYAtqVmRaMQdrUTM%3D", "fstate":  "Papua Barat", "fdescr":  "Telukwondama", "ftzone": 9, "flstfl": 0}, 
{"_id": 587, "fnewid":  "BSVZPlxgUyIBc1AxDTxUZwZyUWUNYlc8UDIBLANgXWIGZAY9XmYGNAJlADcOYFI9", "fstate":  "Riau", "fdescr":  "Bengkalis", "ftzone": 7, "flstfl": 0}, 
{"_id": 588, "fnewid":  "BSUCZVxgVyYGdAVkATBQbFQgAzcHaFQ%2FBWcFKFAzW2QAYlFqDTUDMVA3UmUNY1E%2B", "fstate":  "Riau", "fdescr":  "Indragiri Hilir", "ftzone": 7, "flstfl": 0}, 
{"_id": 589, "fnewid":  "AiIHYFllUyJSIANiDTwLNlAkVGBVOgRvUTMFKFAzCTYFZ1FqDTUCMAViUWZcMlI9", "fstate":  "Riau", "fdescr":  "Indragiri Hulu", "ftzone": 7, "flstfl": 0}, 
{"_id": 590, "fnewid":  "VXVQNwE9BHVTIVQ1CDgEMAB0VGAHaFI5UjADLls4XWIBY1BrADgGNAZhV2AJZwRr", "fstate":  "Riau", "fdescr":  "Kampar", "ftzone": 7, "flstfl": 0}, 
{"_id": 596, "fnewid":  "V3dQNwg0BHVTIQBhATFWZFAkBDBQP1A7A2FWewFiXGNWNFZtCzNUZgdgADcKZARr", "fstate":  "Riau", "fdescr":  "Kepulauan Meranti", "ftzone": 7, "flstfl": 0}, 
{"_id": 598, "fnewid":  "CytQN1llUyJQIgFgWmpRbVElU2cAb1Q%2FA2ECLwNgWWZWNAA7CTECMFUyWG8Bb1Q7", "fstate":  "Riau", "fdescr":  "Dumai Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 597, "fnewid":  "ACBTNAwwAXBUJgNiADAAM1ElV2NXOAVuBmRVeFU2AT4AYldsXWUDMVUyADcNYwFu", "fstate":  "Riau", "fdescr":  "Pekanbaru Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 591, "fnewid":  "VnZWMQ8zUCFXJQtqDj4LPlcjAzcFagdsBWcBLFs4DjEGZAQ%2FDTUAMgptUWYLZVY5", "fstate":  "Riau", "fdescr":  "Kuantan Singingi", "ftzone": 7, "flstfl": 0}, 
{"_id": 592, "fnewid":  "AiIHYAk1BHVQIgRlDDwHMVYiUGRWOQRvUDIALQBjWmVSMAM4W2MHNVYxWW5bNQNs", "fstate":  "Riau", "fdescr":  "Pelalawan", "ftzone": 7, "flstfl": 0}, 
{"_id": 593, "fnewid":  "BSUHYAwwA3IGdAJjCjoKPQJ2Cj4HaAZtVjQEKVY1DDNaOFVuXWUHNVI1UGcIZgFu", "fstate":  "Riau", "fdescr":  "Rokan Hilir", "ftzone": 7, "flstfl": 0}, 
{"_id": 594, "fnewid":  "BSVQN1pmVicBc1Q1XW1RYVMnAzcMYwFqUDJSf1Y1AT5TMQU%2BCzNWZAFmU2QNYwZp", "fstate":  "Riau", "fdescr":  "Rokan Hulu", "ftzone": 7, "flstfl": 0}, 
{"_id": 595, "fnewid":  "UHBYPws3VCUHdQNiXm4GNwJ2UGRVOgRvDW9Sf1c0WWYGZFFqCDBUZgBnWG9ZN1E%2B", "fstate":  "Riau", "fdescr":  "Siak", "ftzone": 7, "flstfl": 0}, 
{"_id": 956, "fnewid":  "CysFYgo2VSRbKVM%2BW2cLOQZyADQFalU%2BDG4CLwBjDTIAYlFqDDQPPVcwVmFZNwFu", "fstate":  "Sulawesi Barat", "fdescr":  "Majene", "ftzone": 8, "flstfl": 0}, 
{"_id": 957, "fnewid":  "UHBXMF1hBHVbKVY7ADwGNQx4UWUAbwFqA2ECL1AzW2RUNgc8DzcAMlA3UGcOYFI9", "fstate":  "Sulawesi Barat", "fdescr":  "Mamasa", "ftzone": 8, "flstfl": 0}, 
{"_id": 953, "fnewid":  "BycCZV1hVCUBcwNuDzNWYQF1ADRVOgBrA2ENIFs4XmEHZQQ%2FDTUBM1E2U2ReMFU6", "fstate":  "Sulawesi Barat", "fdescr":  "Mamuju", "ftzone": 8, "flstfl": 0}, 
{"_id": 954, "fnewid":  "ACBZPltnA3IBcwNuXmIAMFQgBTFXOFQ%2FA2FQfVQ3WmUBYwQ%2FDDRRYwRjUGcBbwFu", "fstate":  "Sulawesi Barat", "fdescr":  "Mamuju Tengah", "ftzone": 8, "flstfl": 0}, 
{"_id": 955, "fnewid":  "BSUEYw8zA3JTIVc6AT1XZgF1UGRVOgJpBGYFKFU2WWZVNw02CjJRYwtsU2QOYAZp", "fstate":  "Sulawesi Barat", "fdescr":  "Mamuju Utara", "ftzone": 8, "flstfl": 0}, 
{"_id": 958, "fnewid":  "VXUHYAg0UiNVJ1A9DTEEOAVxBzNQPwJpVzUGK1IxDTJRM1dsW2MHNVE2U2RaNFU6", "fstate":  "Sulawesi Barat", "fdescr":  "Polewali Mandar", "ftzone": 8, "flstfl": 0}, 
{"_id": 910, "fnewid":  "ACAHYA8zUyJTIVQ5ATlTZ1YiCz8HaAZtUjADLlY1WWZaOAM4XmYBMwZhV2AKZARr", "fstate":  "Sulawesi Selatan", "fdescr":  "Bantaeng", "ftzone": 8, "flstfl": 0}, 
{"_id": 911, "fnewid":  "V3cHYA8zA3JQIlQ5DTVUYQx4UGQEa1I5BWdRfFc0AD9bOVZtCjIHNVI1VWIOYF0y", "fstate":  "Sulawesi Selatan", "fdescr":  "Barru", "ftzone": 8, "flstfl": 0}, 
{"_id": 912, "fnewid":  "BycAZ1llA3JUJgFsW2MCNFYiV2MNYgdsB2UMIVAzAD9bOVdsADgPPVA3BTINY1Q7", "fstate":  "Sulawesi Selatan", "fdescr":  "Bone", "ftzone": 8, "flstfl": 0}, 
{"_id": 913, "fnewid":  "UnIFYgg0A3JTIQVoDzcHMARwCz9WOQFqVTcMIQBjAD8BYww3CzMOPABnBTIOYAZp", "fstate":  "Sulawesi Selatan", "fdescr":  "Bulukumba", "ftzone": 8, "flstfl": 0}, 
{"_id": 914, "fnewid":  "VnYHYA0xUyJXJQpnWWEDM1AkAzdWOQFqAmAMIQNgAD8FZ1ZtCTFUZgtsBTJbNV0y", "fstate":  "Sulawesi Selatan", "fdescr":  "Enrekang", "ftzone": 8, "flstfl": 0}, 
{"_id": 915, "fnewid":  "BCRXMA4yAXAGdFM%2BCDBQYQN3AjYCbVA7UDJXels4DzBUNlFqDDRWZFI1UGdbNVM8", "fstate":  "Sulawesi Selatan", "fdescr":  "Gowa", "ftzone": 8, "flstfl": 0}, 
{"_id": 916, "fnewid":  "BCRTNFtnUyICcAZrXWVXZVMnV2MMYw9kUjABLABjCzRTMQ02CTEAMlYxADcPYQFu", "fstate":  "Sulawesi Selatan", "fdescr":  "Jeneponto", "ftzone": 8, "flstfl": 0}, 
{"_id": 930, "fnewid":  "UXEAZw8zXSxRI1E8W2FUYFMnBjIHaAVuB2VVeFIxAT5SMAI5XmZWZAdgBzBbNVI9", "fstate":  "Sulawesi Selatan", "fdescr":  "Makassar Kota", "ftzone": 8, "flstfl": 0}, 
{"_id": 931, "fnewid":  "UXFXMFtnVyYBcwtmWWNXYlQgBjJQP1Q%2FBmRWewNgAT5VNwY9W2NRY1A3AjVdMwNs", "fstate":  "Sulawesi Selatan", "fdescr":  "Palopo Kota", "ftzone": 8, "flstfl": 0}, 
{"_id": 932, "fnewid":  "VnZYP15iBHVQIgJvADpQZlcjATUDbAdsVTcGK1IxCzQFZww3CzNTYQtsUWYJZwNs", "fstate":  "Sulawesi Selatan", "fdescr":  "Pare-Pare Kota", "ftzone": 8, "flstfl": 0}, 
{"_id": 917, "fnewid":  "BCRUM1llUiNTIQtmCDBUZ1cjBjIAbwFqAGJRfFMwDzACYFVuXmZTYVE2UWZdMwFu", "fstate":  "Sulawesi Selatan", "fdescr":  "Luwu", "ftzone": 8, "flstfl": 0}, 
{"_id": 918, "fnewid":  "BSUAZ1xgVCUHdQJvWmJTbwN3Cj5VOlA7UDIHKgFiXmFSMAI5WWEENgZhUmUIZlI9", "fstate":  "Sulawesi Selatan", "fdescr":  "Luwu Timur", "ftzone": 8, "flstfl": 0}, 
{"_id": 919, "fnewid":  "BycHYF5iAXABc1Q5CzNTblMnCz8EawJpDW8DLlEyAD9SMAM4XGQBMwptVmELZVM8", "fstate":  "Sulawesi Selatan", "fdescr":  "Luwu Utara", "ftzone": 8, "flstfl": 0}, 
{"_id": 920, "fnewid":  "VnYDZA8zAHFXJQJvW2AKPgF1ATUNYlA7BGYBLAZlXWJWNAw3XmZWZFI1AzRcMlE%2B", "fstate":  "Sulawesi Selatan", "fdescr":  "Maros", "ftzone": 8, "flstfl": 0}, 
{"_id": 921, "fnewid":  "AiIHYAA8BHVaKAJvDDcLPlElAjYEawVuVjRVeFQ3W2RSMAY9ATkHNVE2UWYNY1Y5", "fstate":  "Sulawesi Selatan", "fdescr":  "Pangkajene Kepulauan", "ftzone": 8, "flstfl": 0}, 
{"_id": 922, "fnewid":  "AyNWMVxgXC1SIFQ5CDMFM1QgBzMMY1c8VTcCLwFiCDdUNgI5CzMFNwRjADcIZlwz", "fstate":  "Sulawesi Selatan", "fdescr":  "Pinrang", "ftzone": 8, "flstfl": 0}, 
{"_id": 909, "fnewid":  "AiIAZ15iVCVaKANuCjNRbAdzBzNVOlU%2BAmADLlU2DzAGZAc8CjJTYQViV2BcMlA%2F", "fstate":  "Sulawesi Selatan", "fdescr":  "Selayar", "ftzone": 8, "flstfl": 0}, 
{"_id": 923, "fnewid":  "ACBVMgs3USBSIFc6ADtTZFAkBzMDbAJpDG4DLlIxXWJXNVFqXmZWZFI1UmUBbwdo", "fstate":  "Sulawesi Selatan", "fdescr":  "Sidenrengrappang", "ftzone": 8, "flstfl": 0}, 
{"_id": 924, "fnewid":  "VXVZPl5iUSBUJgNuWmECMgB0VGAGaVI5VjRSfwNgDTJRMwU%2BCjIFN1YxU2QIZgdo", "fstate":  "Sulawesi Selatan", "fdescr":  "Sinjai", "ftzone": 8, "flstfl": 0}, 
{"_id": 925, "fnewid":  "UnJTNFllUSBVJ1Y7CTICM1AkVGBVOgNoBmQFKAFiCjVXNVJpDTUFNwBnUWYIZlY5", "fstate":  "Sulawesi Selatan", "fdescr":  "Soppeng", "ftzone": 8, "flstfl": 0}, 
{"_id": 926, "fnewid":  "BycFYg8zXC0AcgFsXGcFNwZyBzMGaVQ%2FUDINIFc0CjUAYgU%2BCDAGNABnU2QIZlY5", "fstate":  "Sulawesi Selatan", "fdescr":  "Takalar", "ftzone": 8, "flstfl": 0}, 
{"_id": 927, "fnewid":  "VXVSNQ4yUCFSIAdqW2AHNA15UWUEawRvBWdWe1s4W2QGZA02WmICMFA3UGdcMl0y", "fstate":  "Sulawesi Selatan", "fdescr":  "Tanatoraja", "ftzone": 8, "flstfl": 0}, 
{"_id": 928, "fnewid":  "UXEDZFxgXSxaKAdqDTYEOAdzUWVVOgVuAWMGKwNgAD8BYwU%2BDDQAMgFmAjVZN1Q7", "fstate":  "Sulawesi Selatan", "fdescr":  "Toraja Utara", "ftzone": 8, "flstfl": 0}, 
{"_id": 929, "fnewid":  "BiZQN11hB3ZXJQdqCDNTblMnVGAGaQVuUTNSf1U2XGNXNVVuXGQAMlYxWW5ZN1A%2F", "fstate":  "Sulawesi Selatan", "fdescr":  "Wajo", "ftzone": 8, "flstfl": 0}, 
{"_id": 896, "fnewid":  "AiJXMF5iUiMBc1Y6CzsHNQF1Cz8MYw5lAGJQfVo5XmEGZAI5ATkENgRjADcNY1Y5", "fstate":  "Sulawesi Tengah", "fdescr":  "Banggai", "ftzone": 8, "flstfl": 0}, 
{"_id": 897, "fnewid":  "UHBYPwg0AXAFdwNvCzsENwJ2AzcHaFc8AGIEKVs4XmEGZAE6CzMHNQViU2RbNVU6", "fstate":  "Sulawesi Tengah", "fdescr":  "Banggai Kepulauan", "ftzone": 8, "flstfl": 0}, 
{"_id": 898, "fnewid":  "V3cDZAs3BndVJ1c7XW1UaAF1U2cAbwNoVjRSf1U2AT4HZQU%2BXWVWZFcwAzQOYAFu", "fstate":  "Sulawesi Tengah", "fdescr":  "Banggai Laut", "ftzone": 8, "flstfl": 0}, 
{"_id": 899, "fnewid":  "VnZVMg0xXC1TIVA8W2tUaQ15AjYFalA7BWcDLgZlCTYHZQA7DTUHNQtsUmVcMgFu", "fstate":  "Sulawesi Tengah", "fdescr":  "Buol", "ftzone": 8, "flstfl": 0}, 
{"_id": 900, "fnewid":  "AyMFYgk1UCFTIQBtXGUKPlElVmJQPwRvAGIHKlY1AD9QMlZtCTEAMgRjUmVbNVM8", "fstate":  "Sulawesi Tengah", "fdescr":  "Donggala", "ftzone": 8, "flstfl": 0}, 
{"_id": 908, "fnewid":  "BCQDZA8zB3ZQIgFsWWAGOgdzCz8DbABrDG4EKQdkXmFbOQc8W2NSYAFmAzReMFQ7", "fstate":  "Sulawesi Tengah", "fdescr":  "Palu Kota", "ftzone": 8, "flstfl": 0}, 
{"_id": 901, "fnewid":  "UnJXMAg0B3YAclA9DTQDNg15VmIBblQ%2FDW8DLls4DDNUNgw3DDQAMgFmVWJaNFI9", "fstate":  "Sulawesi Tengah", "fdescr":  "Morowali", "ftzone": 8, "flstfl": 0}, 
{"_id": 902, "fnewid":  "BiZRNltnUSBRIwNuDjcLPQF1BDBXOFU%2BVjQALQZlXmEFZwU%2BDzcPPQptBTJcMlQ7", "fstate":  "Sulawesi Tengah", "fdescr":  "Morowali Utara", "ftzone": 8, "flstfl": 0}, 
{"_id": 904, "fnewid":  "CioDZA0xVyYGdARpCDEDMw15Cj5VOgFqVjQHKlo5DzBXNQU%2BDTUCMFI1VmFbNQdo", "fstate":  "Sulawesi Tengah", "fdescr":  "Poso", "ftzone": 8, "flstfl": 0}, 
{"_id": 907, "fnewid":  "BSUCZQA8VCVaKFE8WmMGNVQgAzdVOgVuB2UCLwFiDzBVNwU%2BCDBWZAJlBTIIZlM8", "fstate":  "Sulawesi Tengah", "fdescr":  "Sigi", "ftzone": 8, "flstfl": 0}, 
{"_id": 905, "fnewid":  "BCQAZwg0UyJVJwFsDTRWZwF1Cz8DbFM4BmQDLgFiXWJWNAU%2BDjYENlE2BDNeMARr", "fstate":  "Sulawesi Tengah", "fdescr":  "Tojounauna", "ftzone": 8, "flstfl": 0}, 
{"_id": 906, "fnewid":  "CytYPw4yVyZVJ1c6DTQBM1ElVmJXOFU%2BBGYDLgdkCzRTMQI5W2MOPAdgWW4PYVwz", "fstate":  "Sulawesi Tengah", "fdescr":  "Tolitoli", "ftzone": 8, "flstfl": 0}, 
{"_id": 933, "fnewid":  "VnYFYgE9B3YBc1Q5ATtTZFMnU2cHaFc8BWdXelAzAT5RM1VuCjIENgBnVGMLZVY5", "fstate":  "Sulawesi Tenggara", "fdescr":  "Bombana", "ftzone": 8, "flstfl": 0}, 
{"_id": 934, "fnewid":  "CioCZVllUCEGdApnDzUENAB0AjYGaQVuB2UNIFIxDzBVN1VuXWVSYABnBDMKZARr", "fstate":  "Sulawesi Tenggara", "fdescr":  "Buton", "ftzone": 8, "flstfl": 0}, 
{"_id": 935, "fnewid":  "UXFVMltnXSxXJVY7DzULOgVxUWUMY1I5BWdSfwZlCjVQMgM4CzMAMlUyUmUOYFU6", "fstate":  "Sulawesi Tenggara", "fdescr":  "Buton Utara", "ftzone": 8, "flstfl": 0}, 
{"_id": 936, "fnewid":  "AyMCZQk1VSRaKAVoDzUGNA15VmIFalQ%2FVTdRfANgXGMHZVdsDDRUZgViUWZcMlY5", "fstate":  "Sulawesi Tenggara", "fdescr":  "Kolaka", "ftzone": 8, "flstfl": 0}, 
{"_id": 937, "fnewid":  "BiZVMgo2XSxaKANuWWMKOQJ2V2NXOAZtUTMALQdkWWZWNAY9CzNSYAJlVGMKZFc4", "fstate":  "Sulawesi Tenggara", "fdescr":  "Kolaka Timur", "ftzone": 8, "flstfl": 0}, 
{"_id": 938, "fnewid":  "BCRTNA4yVCUGdANuCjAFOQRwBjJWOQJpDG4DLgNgAD9UNg02DTUOPABnADcJZwdo", "fstate":  "Sulawesi Tenggara", "fdescr":  "Kolaka Utara", "ftzone": 8, "flstfl": 0}, 
{"_id": 939, "fnewid":  "BSUAZw8zA3JUJgdqDzUEOVMnATVXOFA7BmRWe1U2DDNRMwM4WWFSYARjVWIPYQFu", "fstate":  "Sulawesi Tenggara", "fdescr":  "Konawe", "ftzone": 8, "flstfl": 0}, 
{"_id": 946, "fnewid":  "UHBTNAk1VSRUJgZrW2YAMgVxAjZWOVU%2BUDJWewRnWWYCYFBrW2MENlI1BDNaNFY5", "fstate":  "Sulawesi Tenggara", "fdescr":  "Konawe Kepulauan", "ftzone": 8, "flstfl": 0}, 
{"_id": 940, "fnewid":  "AiJTNA0xVidUJgFsATxQZA15Cz9QPw9kVjRQfVo5CDdUNlFqWmIDMVI1AzRcMlE%2B", "fstate":  "Sulawesi Tenggara", "fdescr":  "Konawe Selatan", "ftzone": 8, "flstfl": 0}, 
{"_id": 941, "fnewid":  "ACADZFtnXSwGdAtmXWBWYwJ2U2dVOgJpAWMEKVY1CzQAYgE6CjICMFYxUWYAbgFu", "fstate":  "Sulawesi Tenggara", "fdescr":  "Konawe Utara", "ftzone": 8, "flstfl": 0}, 
{"_id": 945, "fnewid":  "AiIHYF1hBncGdAtmXGEDMgF1U2cAb1U%2BA2EFKFAzXmFbOVBrDzcPPQBnAzQOYAZp", "fstate":  "Sulawesi Tenggara", "fdescr":  "Bau-Bau Kota", "ftzone": 8, "flstfl": 0}, 
{"_id": 944, "fnewid":  "VnYAZ1tnUyJSIAtmCjcAMAx4UWVQPwRvVTdXegRnDTIBY1JpCDACMAptAjUIZlI9", "fstate":  "Sulawesi Tenggara", "fdescr":  "Kendari Kota", "ftzone": 8, "flstfl": 0}, 
{"_id": 942, "fnewid":  "BSVQNw8zUiNTIQFsDDEEMlcjCj4CbQFqVjQNIARnDDMCYAc8WmIGNFcwADcLZVI9", "fstate":  "Sulawesi Tenggara", "fdescr":  "Muna", "ftzone": 8, "flstfl": 0}, 
{"_id": 943, "fnewid":  "BCQCZQE9B3YCcAdqDjNXYAx4BjJVOlQ%2FDG4FKAZlW2QAYlFqDzcHNQptV2AAblU6", "fstate":  "Sulawesi Tenggara", "fdescr":  "Wakatobi", "ftzone": 8, "flstfl": 0}, 
{"_id": 881, "fnewid":  "UXEDZAwwUCFRIwFtWmsHMgx4V2MGaQ9kVjQGKwFiAD8AYgU%2BCDAENgJlV2AMYlI6", "fstate":  "Sulawesi Utara", "fdescr":  "Bolaangmongondow", "ftzone": 8, "flstfl": 0}, 
{"_id": 882, "fnewid":  "BCQAZ15iUiMBcwNvW2pRZ1MnBjIBbgNoVzUNIANgXmFWNAQ%2FCTFRYwNkVWIJZ1M7", "fstate":  "Sulawesi Utara", "fdescr":  "Bolaangmongondow Selatan", "ftzone": 8, "flstfl": 0}, 
{"_id": 883, "fnewid":  "AyMHYA8zBndQIlM%2FXm8BNgVxATUAb1A7AmADLgdkAD8FZwY9DDRTYVUyUGcLZVY%2B", "fstate":  "Sulawesi Utara", "fdescr":  "Bolaangmongondow Timur", "ftzone": 8, "flstfl": 0}, 
{"_id": 884, "fnewid":  "UXEEY1pmAHEAclE9Xm8FNQVxCj4FalQ%2FUDJVeFY1CzRQMgc8CjJVZ1I1VGMBb1w0", "fstate":  "Sulawesi Utara", "fdescr":  "Bolaangmongondow Utara", "ftzone": 8, "flstfl": 0}, 
{"_id": 889, "fnewid":  "VnZVMlllXSxXJQZqDj9UaQB0VmINYlI5AmANIFAzDDNQMgc8WmIOPFA3BDMBb1A4", "fstate":  "Sulawesi Utara", "fdescr":  "Kepulauan Sangihe", "ftzone": 8, "flstfl": 0}, 
{"_id": 891, "fnewid":  "BSVWMQA8VCVRI1c7CjpTZgJ2Cj5SPQ9kAWMCLwdkCjVaOAE6ADgENgNkV2BaNAdv", "fstate":  "Sulawesi Utara", "fdescr":  "Kepulauan Siau Tagulandang Biaro", "ftzone": 8, "flstfl": 0}, 
{"_id": 890, "fnewid":  "VnZRNgwwVyYAclc7XGxWYlElU2cCbQZtAmAFKFQ3XGMBY1FqXmYCMAtsVWIJZ1w0", "fstate":  "Sulawesi Utara", "fdescr":  "Kepulauan Talaud", "ftzone": 8, "flstfl": 0}, 
{"_id": 894, "fnewid":  "AiJTNAE9UCFVJwJuDj5WZlYiUGQEa1Q%2FAmBWe1c0XWJUNlVuDjYCMFA3UmUJZwBo", "fstate":  "Sulawesi Utara", "fdescr":  "Bitung Kota", "ftzone": 8, "flstfl": 0}, 
{"_id": 893, "fnewid":  "BSVSNQs3UCEFdwtnXW1QZ1QgBDAFagFqBGYCLwZlAD9SMFdsCDAGNANkBDNdMwdv", "fstate":  "Sulawesi Utara", "fdescr":  "Kotamobagu Kota", "ftzone": 8, "flstfl": 0}, 
{"_id": 892, "fnewid":  "BycAZ1xgVSRXJQJuDDwHMQJ2ADQGaVc8UjAHKgZlDTJTMQQ%2FXGRWZAViUGddMwRs", "fstate":  "Sulawesi Utara", "fdescr":  "Manado Kota", "ftzone": 8, "flstfl": 0}, 
{"_id": 895, "fnewid":  "ACBSNVtnVSQBcwBsWWlUZQVxATUMY1M4UjBRfFo5WWYBY1BrDzcENlcwAzQJZwNr", "fstate":  "Sulawesi Utara", "fdescr":  "Tomohon Kota", "ftzone": 8, "flstfl": 0}, 
{"_id": 885, "fnewid":  "UHBWMVxgAHFWJAZqXm8KOwZyVmJXOAJpB2UNIFY1CDcBYwA7DDRSYANkU2QKZF01", "fstate":  "Sulawesi Utara", "fdescr":  "Minahasa", "ftzone": 8, "flstfl": 0}, 
{"_id": 886, "fnewid":  "UnIHYAs3AXAFdwRoCTgENlcjADQGaQBrBGYALVAzWWYHZQM4CTFWZAZhUWYBb1I6", "fstate":  "Sulawesi Utara", "fdescr":  "Minahasa Selatan", "ftzone": 8, "flstfl": 0}, 
{"_id": 887, "fnewid":  "UHAEYw8zVCVbKVA8ADECMQB0VGANYg9kBGYMIQdkWWZTMVdsCzNVZwJlUGcJZ1I6", "fstate":  "Sulawesi Utara", "fdescr":  "Minahasa Tenggara", "ftzone": 8, "flstfl": 0}, 
{"_id": 888, "fnewid":  "AiICZVpmUiMCcABsXWxRbVMnUGQAbwBrVTcHKlIxW2RWNAw3CDBSYAViVGMPYQZu", "fstate":  "Sulawesi Utara", "fdescr":  "Minahasa Utara", "ftzone": 8, "flstfl": 0}, 
{"_id": 568, "fnewid":  "V3cCZQwwAHFSIFMyAD8APARwCz8DbABrUTMDLgBjDjEHZVZtCDAENgdgAzRZN1c%2F", "fstate":  "Sumatera Barat", "fdescr":  "Agam", "ftzone": 7, "flstfl": 0}, 
{"_id": 569, "fnewid":  "VnYAZ1pmBHVQIlAxAD8FOAB0UWVQPwNoB2VSf1U2WWZaOAI5CTFVZwJlBzBdMwZu", "fstate":  "Sumatera Barat", "fdescr":  "Dharmasraya", "ftzone": 7, "flstfl": 0}, 
{"_id": 571, "fnewid":  "BycHYAs3VyZQIgJjXWNUYVYiVmJVOgZtUDICL1AzCTZSMA02XGRTYVUyBTIMYlA4", "fstate":  "Sumatera Barat", "fdescr":  "Kepulauan Mentawai", "ftzone": 7, "flstfl": 0}, 
{"_id": 582, "fnewid":  "ACAAZwA8VyZUJgdmCThTZQdzVGADbANoUDJWewFiXWJTMVBrDDQHNVYxU2QNY1M7", "fstate":  "Sumatera Barat", "fdescr":  "Bukittinggi Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 580, "fnewid":  "UnJTNA0xUSBUJgtqXWxRZQN3U2cCbQFqVzUDLlU2CjVTMVVuATkENlUyAjVaNFU9", "fstate":  "Sumatera Barat", "fdescr":  "Padang Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 581, "fnewid":  "ACAEY1llUyIHdQJjDD1QZVAkCz9SPQVuA2ENIAFiWWZSMFZtW2NWZFE2WW4BbwRs", "fstate":  "Sumatera Barat", "fdescr":  "Padangpanjang Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 583, "fnewid":  "V3cFYlpmAXABc1Y3CTgLPARwU2dRPlI5BWdSfwFiDDMBY1FqADgENgRjBDNcMlM7", "fstate":  "Sumatera Barat", "fdescr":  "Pariaman Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 584, "fnewid":  "CysAZws3XC1UJgdmDD0ENAB0ATUGaQFqDG4FKANgXmFRMwQ%2FDzdSYAdgUmUIZgZu", "fstate":  "Sumatera Barat", "fdescr":  "Payakumbuh Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 585, "fnewid":  "ACBUMwk1UyJUJlY3W2oHNgJ2VmIBbgVuVzVRfARnXWJXNVBrXWVSYAtsWG8IZlw0", "fstate":  "Sumatera Barat", "fdescr":  "Sawahlunto Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 586, "fnewid":  "BiZUMwwwVidUJgJjCDlRYwJ2AzdSPQRvUTMBLFQ3XWJWNFdsCzMDMQNkADcIZlI6", "fstate":  "Sumatera Barat", "fdescr":  "Solok Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 570, "fnewid":  "AiJWMVllUiNaKFc2CzVTZwF1AzcBblA7DW9We1o5WWZbOQA7DzcDMQtsV2ALZVw0", "fstate":  "Sumatera Barat", "fdescr":  "Limapuluhkoto", "ftzone": 7, "flstfl": 0}, 
{"_id": 572, "fnewid":  "CysHYA4yUSBQIgBhWmRQZgJ2ADQFagFqAGIMIQRnCjUAYgw3DDQPPQNkUGdbNQFp", "fstate":  "Sumatera Barat", "fdescr":  "Padangpariaman", "ftzone": 7, "flstfl": 0}, 
{"_id": 573, "fnewid":  "BSVYP15iAXBaKAZnAD5QZ1AkBTEMYwJpDW8DLlAzWWZTMQw3DzcFN1cwBzABb1Y%2B", "fstate":  "Sumatera Barat", "fdescr":  "Pasaman", "ftzone": 7, "flstfl": 0}, 
{"_id": 574, "fnewid":  "VXVUMwE9UCFUJgJjAT8FNQN3BjIAbwZtVTcGKwZlXWJTMVZtDTVSYFI1ADcJZwBo", "fstate":  "Sumatera Barat", "fdescr":  "Pasaman Barat", "ftzone": 7, "flstfl": 0}, 
{"_id": 575, "fnewid":  "BiYAZws3UyJQIlMyXGIKOwF1AjZVOgRvA2FWe1EyDjEBYwA7ATlUZgptUmUKZFc%2F", "fstate":  "Sumatera Barat", "fdescr":  "Pesisir Selatan", "ftzone": 7, "flstfl": 0}, 
{"_id": 576, "fnewid":  "VnZVMgA8VSQCcAtqWmRTYVMnCz8BbgNoAWMHKlQ3DTJQMgc8XmYBM1A3ADdZN101", "fstate":  "Sumatera Barat", "fdescr":  "Sawahlunto Sijunjung", "ftzone": 7, "flstfl": 0}, 
{"_id": 577, "fnewid":  "VXUFYgs3UiMGdARlCTdUZwRwADQGaQBrBGZQfVEyXmEBY1FqDzdTYQtsVmEIZgBo", "fstate":  "Sumatera Barat", "fdescr":  "Solok", "ftzone": 7, "flstfl": 0}, 
{"_id": 578, "fnewid":  "BydYP1llBHVRIwNiXWMBPVMnV2MEaw9kUjBWe1c0CDdQMgY9XGRUZgtsUmUKZABo", "fstate":  "Sumatera Barat", "fdescr":  "Solok Selatan", "ftzone": 7, "flstfl": 0}, 
{"_id": 579, "fnewid":  "ASFWMQ0xBHUBcwprDTNTblYiBTECbQBrAmBXelU2AT4GZA02CTFVZwFmVGNeMABo", "fstate":  "Sumatera Barat", "fdescr":  "Tanahdatar", "ftzone": 7, "flstfl": 0}, 
{"_id": 610, "fnewid":  "UnJVMl1hAXAGdAtpDDQHMwJ2VmJXOFU%2BA2EFKFQ3W2RTMQE6WWEHNVUyUmULZQNq", "fstate":  "Sumatera Selatan", "fdescr":  "Banyuasin", "ftzone": 7, "flstfl": 0}, 
{"_id": 612, "fnewid":  "BSVTNFpmXSwFdwFjWmIEMg15UWVWOVA7DW8EKVQ3DDMHZVBrDjZWZAJlVGMMYlY%2F", "fstate":  "Sumatera Selatan", "fdescr":  "Empat Lawang", "ftzone": 7, "flstfl": 0}, 
{"_id": 623, "fnewid":  "CipVMgg0UiNbKQZkXWYGMQZyBDADbFQ%2FUTMNIFIxW2RVNwM4WWEAMlUyU2QLZVM6", "fstate":  "Sumatera Selatan", "fdescr":  "Lubuklinggau Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 624, "fnewid":  "VnYHYA0xBHVQIgNhADsCMlcjAzcHaAVuAWMDLgBjCzRTMVVuDzdSYFI1BDMBb1Y%2F", "fstate":  "Sumatera Selatan", "fdescr":  "Pagaralam Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 622, "fnewid":  "UXFYPws3VyZTIQVnXmVWYARwCz9RPlI5VTcEKVc0DzAFZ1dsATkDMQFmU2QPYQZv", "fstate":  "Sumatera Selatan", "fdescr":  "Palembang Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 625, "fnewid":  "BSVRNl1hVSQCcANhADsBMAdzBjJSPQVuVTcEKQdkCjUHZQE6WmJUZgJlAjUJZ1I7", "fstate":  "Sumatera Selatan", "fdescr":  "Prabumulih Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 611, "fnewid":  "UnJYP15iVyYAclQ2CzMHMgx4U2cGaVU%2BB2UGK1Q3W2RbOVJpWmIOPAFmV2ANY1M6", "fstate":  "Sumatera Selatan", "fdescr":  "Lahat", "ftzone": 7, "flstfl": 0}, 
{"_id": 613, "fnewid":  "BSVRNgs3USBVJwNhCTFTZFYiVmIGaQRvUTNRfFU2DDMGZAU%2BADhVZwptU2QKZABp", "fstate":  "Sumatera Selatan", "fdescr":  "Muaraenim", "ftzone": 7, "flstfl": 0}, 
{"_id": 614, "fnewid":  "AyMDZFpmVCUCcAdlXWUKOlYiCj4AbwJpUjBQfQFiXmFWNFBrCDAAMlYxAjVZNwdu", "fstate":  "Sumatera Selatan", "fdescr":  "Musibanyuasin", "ftzone": 7, "flstfl": 0}, 
{"_id": 615, "fnewid":  "UXEEYwg0UCFXJQtpATkKOwJ2Cj5VOlM4UDIFKAZlWmUGZFJpDTVWZFcwBDNeMFU8", "fstate":  "Sumatera Selatan", "fdescr":  "Musirawas", "ftzone": 7, "flstfl": 0}, 
{"_id": 616, "fnewid":  "UnJZPgA8AHFVJwVnATkHNQJ2U2dXOA5lUTMCL1o5CTZXNQA7XWVUZgBnADdeMFw1", "fstate":  "Sumatera Selatan", "fdescr":  "Ogan Ilir", "ftzone": 7, "flstfl": 0}, 
{"_id": 617, "fnewid":  "UHADZA8zAHFVJ1Y0CTFWZQRwAjYFagdsVTcHKgdkXWJQMlZtDzcENgRjUmVbNVQ9", "fstate":  "Sumatera Selatan", "fdescr":  "Ogan Komering Ilir", "ftzone": 7, "flstfl": 0}, 
{"_id": 618, "fnewid":  "BiZXMFpmUiNaKAVnCzMKNgN3VGAEa1c8DW8EKVs4XGNSMAI5DjZVZwZhBzBcMlA5", "fstate":  "Sumatera Selatan", "fdescr":  "Ogan Komering Ulu", "ftzone": 7, "flstfl": 0}, 
{"_id": 619, "fnewid":  "AiICZQk1B3ZaKFc1DTUCP1cjU2cFagNoAWNQfQZlCDcHZVVuXmZUZgViBzBbNQRt", "fstate":  "Sumatera Selatan", "fdescr":  "Ogan Komering Ulu Selatan", "ftzone": 7, "flstfl": 0}, 
{"_id": 620, "fnewid":  "CipXMF5iUSAGdABiCDMDNwB0AjZVOlU%2BVzUMIQBjWmVVNwA7ADgHNVA3AjUNY1Y%2F", "fstate":  "Sumatera Selatan", "fdescr":  "Ogan Komering Ulu Timur", "ftzone": 7, "flstfl": 0}, 
{"_id": 621, "fnewid":  "CysHYFpmUSBUJgZkXGcDNlMnBDBRPgZtVjQCLwFiXGNRMwE6ATlTYQNkAzQOYAFo", "fstate":  "Sumatera Selatan", "fdescr":  "Penukal Abab Lematang Ilir", "ftzone": 7, "flstfl": 0}, 
{"_id": 535, "fnewid":  "BCRYPwg0XSwGdAZnCDJTYgdzV2MDbFQ%2FAmBSf1Q3AD9RMwI5WWECMANkBDMKZABp", "fstate":  "Sumatera Utara", "fdescr":  "Asahan", "ftzone": 7, "flstfl": 0}, 
{"_id": 536, "fnewid":  "ACBTNAo2AXBQIlQ1ADoFN1QgBzMBblI5AWMALVc0CDcAYg02DjYDMQdgBTIPYVE4", "fstate":  "Sumatera Utara", "fdescr":  "Batubara", "ftzone": 7, "flstfl": 0}, 
{"_id": 537, "fnewid":  "V3dXMFxgXC0CcFc2DjRQYwdzBDBWOQVuDW8CLwRnXWIAYlZtATlSYAJlBTINYwFo", "fstate":  "Sumatera Utara", "fdescr":  "Dairi", "ftzone": 7, "flstfl": 0}, 
{"_id": 538, "fnewid":  "ASFSNQs3BndUJlAxWmBTb1YiAjYNYg9kUDIEKVc0DDNaOFJpW2MAMlE2ADdaNFA5", "fstate":  "Sumatera Utara", "fdescr":  "Deliserdang", "ftzone": 7, "flstfl": 0}, 
{"_id": 539, "fnewid":  "V3cFYgk1XC1SIARlWWNUaVYiUWVQP1A7BWcGK1c0DDMFZwQ%2FADgHNQdgAjVdMwRt", "fstate":  "Sumatera Utara", "fdescr":  "Humbang Hasundutan", "ftzone": 7, "flstfl": 0}, 
{"_id": 540, "fnewid":  "AiIFYgwwVidVJwBhAD0FMQRwBTEMYwZtAmAGK1AzCjVQMlJpCDBSYAViUGcNY1Q9", "fstate":  "Sumatera Utara", "fdescr":  "Karo", "ftzone": 7, "flstfl": 0}, 
{"_id": 561, "fnewid":  "UHAAZwA8USAFdwtqDjEGM1ElBjIHaAZtVTdRfANgWmVVNw02W2NTYVA3VWIKZABp", "fstate":  "Sumatera Utara", "fdescr":  "Binjai Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 567, "fnewid":  "CioDZA8zUSACcFMyXWIHNFMnBDAMY1U%2BDG4MIVEyCTZaOAU%2BATlRYwFmV2AOYFM6", "fstate":  "Sumatera Utara", "fdescr":  "Gunung Sitoli Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 560, "fnewid":  "AiJUMw0xUSBTIVY3XWJUYFAkBzMMYwRvVzUDLgNgAD9aOAc8ADhTYQNkUGdZNwRt", "fstate":  "Sumatera Utara", "fdescr":  "Medan Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 562, "fnewid":  "VnZUM15iUiNUJlQ1WWYHMQ15ADQNYgRvDW8NIANgXWICYAQ%2FWmJRYwptWW5aNABp", "fstate":  "Sumatera Utara", "fdescr":  "Padangsidempuan Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 563, "fnewid":  "UnICZQ4yXC0CcARlXmECNVcjUWUCbQJpAmAALQFiCzQBYwc8ATkHNVI1UmVZN100", "fstate":  "Sumatera Utara", "fdescr":  "Pematangsiantar Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 564, "fnewid":  "AyNQN1llBHVSIFY3AT4BMQVxATVSPVA7UjBWe1o5W2RbOVJpXWVSYAZhWG8MYlQ9", "fstate":  "Sumatera Utara", "fdescr":  "Sibolga Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 565, "fnewid":  "VnZUMws3AXBSIANiCjULOgJ2VGADbAdsUTNRfARnDzAGZAI5CzMFN1cwVWIPYVc%2B", "fstate":  "Sumatera Utara", "fdescr":  "Tanjungbalai Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 566, "fnewid":  "ASECZQ0xBncFd1c2WmUFNwJ2ATVXOAdsAWNWewBjXWJaOAw3XGQFNwptBTIMYgdu", "fstate":  "Sumatera Utara", "fdescr":  "Tebingtinggi Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 541, "fnewid":  "CipWMQE9BHVRI1Q1DzJRZFMnCj5VOgRvUTMHKlAzW2RRMwU%2BCDAOPAtsBDMNY1I7", "fstate":  "Sumatera Utara", "fdescr":  "Labuhanbatu", "ftzone": 7, "flstfl": 0}, 
{"_id": 542, "fnewid":  "AiJRNgk1UiNUJlAxWWRRZw15ADQBblQ%2FBGYNIFc0DzBWNAI5WmIDMVA3AjVZN1w1", "fstate":  "Sumatera Utara", "fdescr":  "Labuhanbatu Selatan", "ftzone": 7, "flstfl": 0}, 
{"_id": 543, "fnewid":  "ACBYPwE9VSQFd1Q1CDUEMwB0BTFQPwVuA2EALVo5CTYCYAA7DzcPPQViV2AIZgdu", "fstate":  "Sumatera Utara", "fdescr":  "Labuhanbatu Utara", "ftzone": 7, "flstfl": 0}, 
{"_id": 544, "fnewid":  "CipXMAE9VSRVJ1Q1XGEAMFcjUWVXOA9kAWNQfVY1AT5SMFZtCjIFNwZhBTIAblc%2B", "fstate":  "Sumatera Utara", "fdescr":  "Langkat", "ftzone": 7, "flstfl": 0}, 
{"_id": 545, "fnewid":  "UXEHYF1hXC0HdVMyW2YENQ15Cj4GaQNoBWcCL1AzXmFSMAI5DTVUZgptUWZdM1A5", "fstate":  "Sumatera Utara", "fdescr":  "Mandailing Natal", "ftzone": 7, "flstfl": 0}, 
{"_id": 546, "fnewid":  "VXUHYF5iVyYFd1c2AD0HNQ15BjJSPQJpA2EDLlc0CzRVNwU%2BCDADMVA3UGddM1Y%2F", "fstate":  "Sumatera Utara", "fdescr":  "Nias", "ftzone": 7, "flstfl": 0}, 
{"_id": 547, "fnewid":  "ACBUM1pmBHVXJQJjXWAFNlYiUWVVOgJpBmQCL1AzW2QAYldsWmJVZwptADcOYFM6", "fstate":  "Sumatera Utara", "fdescr":  "Nias Barat", "ftzone": 7, "flstfl": 0}, 
{"_id": 548, "fnewid":  "ACAEY1llUiMCcFMyXmMDPwRwCz8HaFQ%2FVjRXegRnDTJWNFVuDjZUZgtsADcIZlU8", "fstate":  "Sumatera Utara", "fdescr":  "Nias Selatan", "ftzone": 7, "flstfl": 0}, 
{"_id": 549, "fnewid":  "VnZZPgE9UiMFdwRlWmdQbQRwV2MMY1M4VzUCL1AzCTZUNlBrCzMCMAViVmEOYFc%2B", "fstate":  "Sumatera Utara", "fdescr":  "Nias Utara", "ftzone": 7, "flstfl": 0}, 
{"_id": 558, "fnewid":  "BydTNFllUSBXJQZnDjJUaA15BTEDbFA7A2EBLFEyDjEGZAY9XGRSYAdgVWINY1E4", "fstate":  "Sumatera Utara", "fdescr":  "Padang Lawas", "ftzone": 7, "flstfl": 0}, 
{"_id": 559, "fnewid":  "VnZSNQo2A3JTIVAxADxXalElU2cNYgZtAWNWewBjDjEBY1JpDDRTYVYxADdaNFU8", "fstate":  "Sumatera Utara", "fdescr":  "Padang Lawas Utara", "ftzone": 7, "flstfl": 0}, 
{"_id": 550, "fnewid":  "VnZRNgk1B3YGdFc2DTECNg15VGAEawJpUjAGK1EyCzRVNwY9W2MDMQBnU2QJZ1I7", "fstate":  "Sumatera Utara", "fdescr":  "Pakpakbharat", "ftzone": 7, "flstfl": 0}, 
{"_id": 551, "fnewid":  "VnZWMQg0A3JWJABhCDQGM1MnVGAEaw5lDG4FKABjDjEGZFJpDjYHNVYxBTILZVE4", "fstate":  "Sumatera Utara", "fdescr":  "Samosir", "ftzone": 7, "flstfl": 0}, 
{"_id": 553, "fnewid":  "V3dUMwA8BncBcwZnWmYHMFMnATUCbQJpDG5VeFAzDzBRMwY9DDRRY1YxAjULZVU8", "fstate":  "Sumatera Utara", "fdescr":  "Serdang Bedagai", "ftzone": 7, "flstfl": 0}, 
{"_id": 554, "fnewid":  "ASFWMVllUyJTIQVkXWFXZwF1BjIFagJpDW9XegdkCTZSMFZtCTFTYQRjWW5ZN1A5", "fstate":  "Sumatera Utara", "fdescr":  "Simalungun", "ftzone": 7, "flstfl": 0}, 
{"_id": 555, "fnewid":  "BSUAZw8zVidbKVAxXWEENQx4ADQMY1Q%2FBmQDLls4WWZWNAI5CjIOPARjBTILZVI7", "fstate":  "Sumatera Utara", "fdescr":  "Tapanuli Selatan", "ftzone": 7, "flstfl": 0}, 
{"_id": 556, "fnewid":  "BCRRNgA8BndaKAprCzdTYVElCj5QPwBrB2VVeAFiWmUHZQ02XWUBMwZhV2ALZVY%2F", "fstate":  "Sumatera Utara", "fdescr":  "Tapanuli Tengah", "ftzone": 7, "flstfl": 0}, 
{"_id": 557, "fnewid":  "UHBZPgE9UCFRIwJjCDQDMAF1BzNWOQJpUjBSfwdkDTIBY1FqCjJUZgtsWW4NY1I7", "fstate":  "Sumatera Utara", "fdescr":  "Tapanuli Utara", "ftzone": 7, "flstfl": 0}, 
{"_id": 552, "fnewid":  "UnJQN1llXC1WJAdmADwANgF1BDAHaFc8A2EHKlIxCDdbOQA7ATkCMAJlVmEJZwBp", "fstate":  "Sumatera Utara", "fdescr":  "Tobasamosir", "ftzone": 7, "flstfl": 0}, 
{"_id": 779, "fnewid":  "UXECZQ0xVicCcAVmCzUEOQJ2AjYCbVc8AWNXegZlDjFaOAI5WWEAMgRjBzABb1I7", "fstate":  "Yogyakarta", "fdescr":  "Bantul", "ftzone": 7, "flstfl": 0}, 
{"_id": 780, "fnewid":  "ACBXMFpmA3JWJAVmXG0BNVElU2cNYgZtUDJRfAFiDTJXNVBrCTEGNAdgUGcLZQNq", "fstate":  "Yogyakarta", "fdescr":  "Gunungkidul", "ftzone": 7, "flstfl": 0}, 
{"_id": 783, "fnewid":  "BSUDZAA8A3IHdVY1DD0FMgVxUWUFalI5BWdXelY1W2QHZQQ%2FWmIDMQZhAzRcMgZv", "fstate":  "Yogyakarta", "fdescr":  "Yogyakarta Kota", "ftzone": 7, "flstfl": 0}, 
{"_id": 781, "fnewid":  "ACAFYlxgB3YCcFc0DTxTZgZyUWVRPgBrB2UGKwdkAT5TMVBrXWUDMQptWW4JZ1Q9", "fstate":  "Yogyakarta", "fdescr":  "Kulonprogo", "ftzone": 7, "flstfl": 0}, 
{"_id": 782, "fnewid":  "UXFZPlllUSBaKAJhADEBNwRwVmIDbAZtB2UFKABjAD9TMVZtW2MDMQBnVmEMYlI7", "fstate":  "Yogyakarta", "fdescr":  "Sleman", "ftzone": 7, "flstfl": 0}
]


def main():
    db.czones.insert_many(CZONES_CONTENTS)

if __name__ == '__main__':
    main()